<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from '../../utils/elementFeedback.js'
import { useRouter } from 'vue-router'
import { apiErrorMessage } from '../../api/http.js'
import { getCompleteAnalytics, listAnalyticsSnapshots, rebuildCompleteAnalytics } from '../../api/analytics.js'
import { confirmDataDeletion, exportMyData, previewDataDeletion } from '../../api/privacy.js'
import { useAuthStore } from '../../stores/auth.js'
import { displayText } from '../../utils/displayText.js'

const loading=ref(true), actionLoading=ref(false), analytics=ref(null), snapshots=ref([]), activeDimension=ref('PLATFORM'), range=ref(defaultRange()), deletePreview=ref(null), deletePhrase=ref('')
const router=useRouter(), auth=useAuthStore()
const dimensionRows=computed(()=>analytics.value?.dimensions?.[activeDimension.value]||[])
onMounted(load)
async function load(){loading.value=true;try{const params={from:range.value[0],to:range.value[1]};const [a,s]=await Promise.all([getCompleteAnalytics(params),listAnalyticsSnapshots()]);analytics.value=a.data.data;snapshots.value=s.data.data}catch(e){ElMessage.error(apiErrorMessage(e,'数据分析加载失败'))}finally{loading.value=false}}
async function rebuild(){actionLoading.value=true;try{await rebuildCompleteAnalytics({from:range.value[0],to:range.value[1]},`analytics-ui-${crypto.randomUUID()}`);ElMessage.success('不可变数据快照已生成');await load()}catch(e){ElMessage.error(apiErrorMessage(e,'快照生成失败'))}finally{actionLoading.value=false}}
async function download(){try{const response=await exportMyData(),blob=new Blob([JSON.stringify(response.data.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`jobpilot-export-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);ElMessage.success('导出文件已在本机生成')}catch(e){ElMessage.error(apiErrorMessage(e,'导出失败'))}}
async function previewDelete(){try{const response=await previewDataDeletion(`privacy-preview-ui-${crypto.randomUUID()}`);deletePreview.value=response.data.data;deletePhrase.value=''}catch(e){ElMessage.error(apiErrorMessage(e,'删除预览失败'))}}
async function confirmDelete(){if(deletePhrase.value!==deletePreview.value.confirmationPhrase)return ElMessage.warning('请输入完全一致的确认短语');try{await ElMessageBox.confirm('此操作会停用账号并逻辑删除全部用户业务数据。','最终确认',{type:'error'});await confirmDataDeletion({requestId:deletePreview.value.requestId,requestVersion:deletePreview.value.requestVersion,confirmationPhrase:deletePhrase.value},`privacy-confirm-ui-${crypto.randomUUID()}`);await auth.logout();router.replace('/login')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(apiErrorMessage(e,'删除失败'))}}
function defaultRange(){const to=new Date(),from=new Date();from.setDate(to.getDate()-89);return [iso(from),iso(to)]}function iso(v){return v.toISOString().slice(0,10)}function rate(v){return v==null?'—':`${Number(v).toFixed(2)}%`}
</script>
<template><section v-loading="loading" class="page-section analytics-center"><div class="page-heading"><div><p class="eyebrow accent">阶段 9 · 基于事实的指标</p><h1>数据分析</h1><p>每个转化率都公开分子、分母与样本量；零分母显示未知。</p></div><div class="heading-actions"><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD"/><el-button @click="load">刷新</el-button><el-button type="primary" :loading="actionLoading" @click="rebuild">生成快照</el-button></div></div>
<template v-if="analytics"><section class="surface analytics-funnel"><div class="section-heading"><div><span class="section-kicker">端到端漏斗</span><h2>真实转化漏斗</h2></div><span>时区 {{analytics.timezone}}</span></div><div><article v-for="item in analytics.funnel" :key="item.key"><span>{{displayText(item.label)}}</span><strong>{{item.numerator}}</strong><em>{{rate(item.rate)}}</em><small>{{item.numerator}} / {{item.denominator}} · 样本 {{item.sampleSize}}</small></article></div></section>
<section class="surface dimension-panel"><header><div><span class="section-kicker">转化维度</span><h2>Offer 转化维度</h2></div><div class="dimension-tabs"><button v-for="key in Object.keys(analytics.dimensions)" :key="key" :class="{active:key===activeDimension}" @click="activeDimension=key">{{displayText(key)}}</button></div></header><div class="dimension-head"><span>分组</span><span>Offer / 申请</span><span>样本</span><span>转化率</span></div><div v-for="item in dimensionRows" :key="item.key" class="dimension-row"><strong>{{displayText(item.label)}}</strong><span>{{item.numerator}} / {{item.denominator}}</span><span>{{item.sampleSize}}<small v-if="item.insufficientSample">样本不足</small></span><em>{{rate(item.rate)}}</em></div><div v-if="!dimensionRows.length" class="empty-state compact">当前区间没有可用样本。</div></section>
<div class="analytics-bottom"><section class="surface snapshot-list"><div class="section-heading"><div><span class="section-kicker">不可变历史</span><h2>快照历史</h2></div><strong>{{snapshots.length}}</strong></div><article v-for="item in snapshots" :key="item.id"><div><strong>{{item.from}} → {{item.to}}</strong><span>{{item.schemaVersion}} · {{item.rowCount}} 行</span></div><time>{{new Date(item.generatedAt).toLocaleString('zh-CN')}}</time></article><div v-if="!snapshots.length" class="empty-state compact">尚无重建快照。</div></section>
<section class="surface privacy-panel"><span class="section-kicker">隐私控制</span><h2>数据导出与删除</h2><p>导出不包含密码、令牌或认证密钥。删除采用预览、精确短语和最终确认三重保护。</p><el-button @click="download">导出我的数据</el-button><el-button type="danger" plain @click="previewDelete">预览删除范围</el-button><div v-if="deletePreview" class="delete-confirm"><strong>预计影响 {{Object.values(deletePreview.affectedRecords).reduce((a,b)=>a+b,0)}} 条记录</strong><span>{{deletePreview.warning}}</span><code>{{deletePreview.confirmationPhrase}}</code><el-input v-model="deletePhrase" placeholder="输入上方确认短语"/><el-button type="danger" :disabled="deletePhrase!==deletePreview.confirmationPhrase" @click="confirmDelete">停用账号并删除数据</el-button></div></section></div></template></section></template>
