<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from '../../utils/elementFeedback.js'
import { apiErrorMessage } from '../../api/http.js'
import { displayText, displayBoolean } from '../../utils/displayText.js'
import { cancelTask, createRule, decideSuggestion, getAutomationDashboard, listAuthorizations, listNotifications, listRules, listSuggestions, listTasks, readNotification, retryTask, runRule, updateRule } from '../../api/automationCenter.js'

const loading=ref(true),working=ref(false),dashboard=ref(null),rules=ref([]),tasks=ref([]),suggestions=ref([]),notifications=ref([]),authorizations=ref([]),dialog=ref(false)
const form=reactive({name:'每日岗位摘要',ruleType:'DAILY_JOB_DIGEST',scheduleExpression:'0 0 9 * * *',timezone:'Asia/Shanghai',enabled:false,maxAttempts:3,config:{}})
onMounted(load)
async function load(){loading.value=true;try{const [d,r,t,s,n,a]=await Promise.all([getAutomationDashboard(),listRules(),listTasks(),listSuggestions(),listNotifications(),listAuthorizations()]);dashboard.value=d.data.data;rules.value=r.data.data;tasks.value=t.data.data;suggestions.value=s.data.data;notifications.value=n.data.data;authorizations.value=a.data.data}catch(e){ElMessage.error(apiErrorMessage(e,'安全自动化数据加载失败'))}finally{loading.value=false}}
async function saveRule(){await act(async()=>{await createRule({...form});dialog.value=false;ElMessage.success('规则已保存；调度默认关闭');await load()})}
async function toggle(rule){await act(async()=>{await updateRule(rule.id,{version:rule.version,enabled:!rule.enabled});await load()})}
async function execute(rule,defer=false){await act(async()=>{await runRule(rule.id,{defer},`rule-ui-${crypto.randomUUID()}`);ElMessage.success(defer?'已创建待处理任务':'本地安全处理器已执行');await load()})}
async function cancel(item){await act(async()=>{await cancelTask(item);await load()})}async function retry(item){await act(async()=>{await retryTask(item);await load()})}
async function decide(item,value){try{await ElMessageBox.confirm(value==='accept'?'接受只记录决定，不会删除任何岗位。':'确认忽略该建议？','人工决定');await act(async()=>{await decideSuggestion(item,value);await load()})}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(apiErrorMessage(e,'建议处理失败'))}}
async function markRead(item){await act(async()=>{await readNotification(item);await load()})}
async function act(fn){working.value=true;try{await fn()}catch(e){ElMessage.error(apiErrorMessage(e,'操作失败'))}finally{working.value=false}}
function state(value){return String(value||'').toLowerCase()}
</script>

<template><section v-loading="loading" class="page-section phase10-center"><div class="page-heading"><div><p class="eyebrow accent">阶段 10 · 本地安全处理器</p><h1>安全自动化</h1><p>只整理、重评估、生成建议与站内提醒；不发送消息、不提交申请、不删除重复岗位。</p></div><div class="heading-actions"><el-button @click="load">刷新</el-button><el-button type="primary" @click="dialog=true">新建规则</el-button></div></div>
<template v-if="dashboard"><div class="safety-banner"><strong>调度器 {{dashboard.schedulerEnabled?'已显式开启':'默认关闭'}}</strong><span>手动运行仍受固定处理器白名单与数据库安全约束保护。所有外部动作继续保持“仅手动”。</span></div><div class="metrics-grid phase10-metrics"><article class="metric accent"><span>启用规则</span><strong>{{dashboard.activeRules}}</strong></article><article class="metric"><span>暂停规则</span><strong>{{dashboard.pausedRules}}</strong></article><article class="metric"><span>待处理任务</span><strong>{{dashboard.pendingTasks}}</strong></article><article class="metric"><span>待审建议</span><strong>{{dashboard.pendingSuggestions}}</strong></article><article class="metric"><span>未读提醒</span><strong>{{dashboard.unreadNotifications}}</strong></article></div>
<div class="automation-grid"><section class="surface automation-rules"><div class="section-heading"><div><span class="section-kicker">白名单规则</span><h2>规则与计划</h2></div><strong>{{rules.length}}</strong></div><article v-for="rule in rules" :key="rule.id"><div><strong>{{rule.name}}</strong><span>{{displayText(rule.ruleType)}} · {{rule.scheduleExpression}} · {{rule.timezone}}</span></div><span :class="['status-mark',rule.enabled?'safe':'muted']">{{displayText(rule.status)}}</span><div class="row-actions"><el-button size="small" @click="execute(rule)">立即安全运行</el-button><el-button size="small" @click="execute(rule,true)">仅排队</el-button><el-button size="small" @click="toggle(rule)">{{rule.enabled?'暂停':'启用规则'}}</el-button></div></article><div v-if="!rules.length" class="empty-state">尚无规则。创建后仍不会自动投递或发送消息。</div></section>
<section class="surface automation-tasks"><div class="section-heading"><div><span class="section-kicker">幂等任务</span><h2>执行记录</h2></div><strong>{{tasks.length}}</strong></div><article v-for="task in tasks.slice(0,12)" :key="task.id"><div><strong>{{displayText(task.taskType)}}</strong><span>{{new Date(task.createdAt).toLocaleString('zh-CN')}} · 尝试 {{task.attemptCount}}/{{task.maxAttempts}}</span></div><span :class="['status-mark',state(task.status)]">{{displayText(task.status)}}</span><small>外部消息：{{displayBoolean(task.externalMessageSent)}} · 外部提交：{{displayBoolean(task.externalSubmission)}} · 外部变更：{{displayBoolean(task.externalMutation)}} · 需要确认：{{displayBoolean(task.userConfirmationRequired)}}</small><div class="row-actions"><el-button v-if="task.status==='PENDING'" size="small" @click="cancel(task)">取消</el-button><el-button v-if="['FAILED','BLOCKED'].includes(task.status)" size="small" @click="retry(task)">重试</el-button></div></article><div v-if="!tasks.length" class="empty-state compact">尚无任务。</div></section></div>
<div class="automation-grid lower"><section class="surface automation-rules"><div class="section-heading"><div><span class="section-kicker">人工决策</span><h2>建议</h2></div><strong>{{suggestions.length}}</strong></div><article v-for="item in suggestions" :key="item.id"><div><strong>{{item.title}}</strong><span>{{item.body}}</span></div><span :class="['status-mark',state(item.status)]">{{displayText(item.status)}}</span><div v-if="item.status==='PENDING'" class="row-actions"><el-button size="small" @click="decide(item,'dismiss')">忽略</el-button><el-button size="small" type="primary" @click="decide(item,'accept')">接受记录</el-button></div></article><div v-if="!suggestions.length" class="empty-state compact">没有待审建议。</div></section><section class="surface automation-tasks"><div class="section-heading"><div><span class="section-kicker">仅站内</span><h2>站内提醒</h2></div><strong>{{notifications.length}}</strong></div><article v-for="item in notifications" :key="item.id"><div><strong>{{item.title}}</strong><span>{{item.body}}</span></div><span :class="['status-mark',state(item.status)]">{{displayText(item.status)}}</span><el-button v-if="item.status==='UNREAD'" size="small" @click="markRead(item)">标为已读</el-button></article><div v-if="!notifications.length" class="empty-state compact">没有站内提醒。</div></section></div>
<section class="surface authorization-strip"><div><span class="section-kicker">明确授权</span><h2>授权证据与策略降级</h2><p>当前 {{authorizations.length}} 条授权记录。授权过期、撤销、平台策略未知或过期时自动降级为“仅手动”；阶段 10 即使授权外部范围也没有执行处理器。</p></div><div class="boundary-tags"><span v-for="item in dashboard.safetyBoundaries" :key="item">{{item}}</span></div></section></template>
<el-dialog v-model="dialog" title="创建安全自动化规则" width="560px"><el-form label-position="top"><el-form-item label="规则名称"><el-input v-model="form.name" maxlength="160"/></el-form-item><el-form-item label="固定处理器"><el-select v-model="form.ruleType" style="width:100%"><el-option v-for="type in dashboard?.allowedHandlers||[]" :key="type" :label="displayText(type)" :value="type"/></el-select></el-form-item><div class="form-grid two"><el-form-item label="Spring 定时表达式"><el-input v-model="form.scheduleExpression"/></el-form-item><el-form-item label="IANA 时区"><el-input v-model="form.timezone"/></el-form-item></div><el-form-item><el-checkbox v-model="form.enabled">启用规则（全局调度器默认仍关闭）</el-checkbox></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="working" @click="saveRule">保存规则</el-button></template></el-dialog></section></template>
