ALTER TABLE recommendation_events
    DROP CHECK chk_recommendation_events_type,
    ADD COLUMN viewed_marker TINYINT GENERATED ALWAYS AS (CASE WHEN event_type='VIEWED' THEN 1 ELSE NULL END) STORED,
    ADD UNIQUE KEY uk_recommendation_events_first_view (recommendation_id, viewed_marker),
    ADD CONSTRAINT chk_recommendation_events_type CHECK (event_type IN ('FAVORITE','UNFAVORITE','IGNORE','RESTORE','VIEWED'));

CREATE TABLE feedback (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    job_match_id BIGINT UNSIGNED NOT NULL,
    application_id BIGINT UNSIGNED NULL,
    source_type VARCHAR(32) NOT NULL,
    source_public_id CHAR(26) NOT NULL,
    event_type VARCHAR(24) NOT NULL,
    label_value DECIMAL(6,4) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    feature_schema_version VARCHAR(40) NOT NULL,
    feature_snapshot_json JSON NOT NULL,
    feature_hash CHAR(64) NOT NULL,
    source VARCHAR(24) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_feedback_public_id (public_id),
    UNIQUE KEY uk_feedback_source_event (user_id, source_type, source_public_id, event_type),
    KEY idx_feedback_user_time (user_id, occurred_at, id),
    KEY idx_feedback_job_event (job_id, event_type, occurred_at),
    CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_feedback_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_feedback_match FOREIGN KEY (job_match_id) REFERENCES job_matches (id) ON DELETE RESTRICT,
    CONSTRAINT fk_feedback_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT chk_feedback_source_type CHECK (source_type IN ('RECOMMENDATION_EVENT','APPLICATION','APPLICATION_LOG','INTERVIEW','OFFER')),
    CONSTRAINT chk_feedback_event CHECK (event_type IN ('VIEWED','APPLIED','REPLIED','INTERVIEW','OFFER')),
    CONSTRAINT chk_feedback_label CHECK (label_value BETWEEN 0 AND 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE feedback_rebuild_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    created_count INT UNSIGNED NOT NULL,
    reused_count INT UNSIGNED NOT NULL,
    skipped_no_historical_match INT UNSIGNED NOT NULL,
    leakage_safe TINYINT(1) NOT NULL,
    status VARCHAR(24) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_feedback_rebuild_runs_public_id (public_id),
    UNIQUE KEY uk_feedback_rebuild_runs_idempotency (user_id, idempotency_key),
    KEY idx_feedback_rebuild_runs_user_time (user_id, created_at DESC),
    CONSTRAINT fk_feedback_rebuild_runs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_feedback_rebuild_runs_status CHECK (status IN ('SUCCEEDED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ltr_training_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    cutoff_at DATETIME(3) NULL,
    minimum_sample INT UNSIGNED NOT NULL,
    sample_count INT UNSIGNED NOT NULL,
    train_count INT UNSIGNED NOT NULL,
    validation_count INT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL,
    feature_schema_version VARCHAR(40) NOT NULL,
    leakage_safe TINYINT(1) NOT NULL,
    metrics_json JSON NOT NULL,
    parameters_json JSON NOT NULL,
    error_message_safe VARCHAR(1000) NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ltr_training_runs_public_id (public_id),
    UNIQUE KEY uk_ltr_training_runs_idempotency (user_id, idempotency_key),
    KEY idx_ltr_training_runs_user_time (user_id, created_at DESC),
    CONSTRAINT fk_ltr_training_runs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_ltr_training_runs_status CHECK (status IN ('INSUFFICIENT_DATA','EVALUATED','REJECTED','FAILED')),
    CONSTRAINT chk_ltr_training_runs_counts CHECK (sample_count = train_count + validation_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ltr_model_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    training_run_id BIGINT UNSIGNED NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    model_type VARCHAR(40) NOT NULL,
    feature_schema_json JSON NOT NULL,
    parameters_json JSON NOT NULL,
    training_window_json JSON NOT NULL,
    sample_count INT UNSIGNED NOT NULL,
    evaluation_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL,
    activation_eligible TINYINT(1) NOT NULL,
    shadowed_at DATETIME(3) NULL,
    activated_at DATETIME(3) NULL,
    retired_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status='ACTIVE' THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ltr_model_versions_public_id (public_id),
    UNIQUE KEY uk_ltr_model_versions_version (user_id, version_no),
    UNIQUE KEY uk_ltr_model_versions_active (user_id, active_marker),
    KEY idx_ltr_model_versions_user_status (user_id, status, version_no DESC),
    CONSTRAINT fk_ltr_model_versions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ltr_model_versions_run FOREIGN KEY (training_run_id) REFERENCES ltr_training_runs (id) ON DELETE RESTRICT,
    CONSTRAINT chk_ltr_model_versions_type CHECK (model_type = 'CONSERVATIVE_LINEAR'),
    CONSTRAINT chk_ltr_model_versions_status CHECK (status IN ('DRAFT','SHADOW','ACTIVE','RETIRED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ltr_shadow_results (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    model_version_id BIGINT UNSIGNED NOT NULL,
    recommendation_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    current_score DECIMAL(6,2) NULL,
    shadow_score DECIMAL(6,2) NULL,
    score_delta DECIMAL(7,2) NULL,
    current_rank_position INT UNSIGNED NOT NULL,
    shadow_rank_position INT UNSIGNED NOT NULL,
    feature_snapshot_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ltr_shadow_results_public_id (public_id),
    UNIQUE KEY uk_ltr_shadow_results_model_rec (model_version_id, recommendation_id),
    KEY idx_ltr_shadow_results_user_model (user_id, model_version_id, shadow_rank_position),
    CONSTRAINT fk_ltr_shadow_results_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ltr_shadow_results_model FOREIGN KEY (model_version_id) REFERENCES ltr_model_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ltr_shadow_results_recommendation FOREIGN KEY (recommendation_id) REFERENCES job_recommendations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ltr_shadow_results_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    rule_type VARCHAR(48) NOT NULL,
    schedule_expression VARCHAR(120) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    config_json JSON NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'PAUSED',
    max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
    last_run_at DATETIME(3) NULL,
    next_run_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_rules_public_id (public_id),
    UNIQUE KEY uk_automation_rules_name (user_id, name, deleted_at),
    KEY idx_automation_rules_due (enabled, status, next_run_at, id),
    KEY idx_automation_rules_user (user_id, status, updated_at DESC),
    CONSTRAINT fk_automation_rules_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_rules_type CHECK (rule_type IN ('DAILY_JOB_DIGEST','SAFE_REEVALUATION','DUPLICATE_CLEANUP_SUGGESTION','HIGH_MATCH_REMINDER','FOLLOW_UP_REMINDER','INTERVIEW_REMINDER','OFFER_DEADLINE_REMINDER')),
    CONSTRAINT chk_automation_rules_status CHECK (status IN ('ACTIVE','PAUSED')),
    CONSTRAINT chk_automation_rules_attempts CHECK (max_attempts BETWEEN 1 AND 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE safe_automation_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    automation_rule_id BIGINT UNSIGNED NOT NULL,
    task_type VARCHAR(48) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    input_json JSON NOT NULL,
    output_json JSON NOT NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT UNSIGNED NOT NULL DEFAULT 3,
    scheduled_at DATETIME(3) NOT NULL,
    next_retry_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    error_code VARCHAR(80) NULL,
    error_message_safe VARCHAR(1000) NULL,
    trace_id VARCHAR(64) NULL,
    external_message_sent TINYINT(1) NOT NULL DEFAULT 0,
    external_submission TINYINT(1) NOT NULL DEFAULT 0,
    external_mutation TINYINT(1) NOT NULL DEFAULT 0,
    user_confirmation_required TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_safe_automation_tasks_public_id (public_id),
    UNIQUE KEY uk_safe_automation_tasks_idempotency (user_id, idempotency_key),
    KEY idx_safe_automation_tasks_user_time (user_id, created_at DESC),
    KEY idx_safe_automation_tasks_retry (status, next_retry_at, id),
    CONSTRAINT fk_safe_automation_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_safe_automation_tasks_rule FOREIGN KEY (automation_rule_id) REFERENCES automation_rules (id) ON DELETE RESTRICT,
    CONSTRAINT chk_safe_automation_tasks_type CHECK (task_type IN ('DAILY_JOB_DIGEST','SAFE_REEVALUATION','DUPLICATE_CLEANUP_SUGGESTION','HIGH_MATCH_REMINDER','FOLLOW_UP_REMINDER','INTERVIEW_REMINDER','OFFER_DEADLINE_REMINDER')),
    CONSTRAINT chk_safe_automation_tasks_status CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','BLOCKED','CANCELLED')),
    CONSTRAINT chk_safe_automation_tasks_no_external CHECK (external_message_sent=0 AND external_submission=0 AND external_mutation=0 AND user_confirmation_required=1),
    CONSTRAINT chk_safe_automation_tasks_attempts CHECK (attempt_count <= max_attempts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_suggestions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    automation_rule_id BIGINT UNSIGNED NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    dedup_key CHAR(64) NOT NULL,
    suggestion_type VARCHAR(48) NOT NULL,
    resource_type VARCHAR(48) NOT NULL,
    resource_id VARCHAR(64) NULL,
    title VARCHAR(240) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    evidence_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    decided_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_suggestions_public_id (public_id),
    UNIQUE KEY uk_automation_suggestions_dedup (user_id, dedup_key),
    KEY idx_automation_suggestions_user_status (user_id, status, created_at DESC),
    CONSTRAINT fk_automation_suggestions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_suggestions_rule FOREIGN KEY (automation_rule_id) REFERENCES automation_rules (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_suggestions_task FOREIGN KEY (task_id) REFERENCES safe_automation_tasks (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_suggestions_status CHECK (status IN ('PENDING','ACCEPTED','DISMISSED','EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    dedup_key CHAR(64) NOT NULL,
    notification_type VARCHAR(48) NOT NULL,
    title VARCHAR(240) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    resource_type VARCHAR(48) NULL,
    resource_id VARCHAR(64) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'UNREAD',
    read_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_notifications_public_id (public_id),
    UNIQUE KEY uk_automation_notifications_dedup (user_id, dedup_key),
    KEY idx_automation_notifications_user_status (user_id, status, created_at DESC),
    CONSTRAINT fk_automation_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_notifications_task FOREIGN KEY (task_id) REFERENCES safe_automation_tasks (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_notifications_status CHECK (status IN ('UNREAD','READ','DISMISSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_authorizations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    platform VARCHAR(80) NOT NULL,
    scopes_json JSON NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    evidence_type VARCHAR(48) NOT NULL,
    evidence_ref VARCHAR(500) NOT NULL,
    granted_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    status VARCHAR(24) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status='ACTIVE' THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_authorizations_public_id (public_id),
    UNIQUE KEY uk_automation_authorizations_active (user_id, platform, scope_hash, active_marker),
    KEY idx_automation_authorizations_user_status (user_id, status, expires_at),
    CONSTRAINT fk_automation_authorizations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_authorizations_status CHECK (status IN ('ACTIVE','REVOKED','EXPIRED')),
    CONSTRAINT chk_automation_authorizations_window CHECK (expires_at > granted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
