CREATE TABLE ai_budget_policies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    daily_token_limit BIGINT UNSIGNED NULL,
    monthly_token_limit BIGINT UNSIGNED NULL,
    daily_cost_limit DECIMAL(16,6) NULL,
    monthly_cost_limit DECIMAL(16,6) NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    warning_threshold_percent DECIMAL(5,2) NOT NULL DEFAULT 80.00,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_budget_policies_public_id (public_id),
    UNIQUE KEY uk_ai_budget_policies_active (user_id, active_marker),
    KEY idx_ai_budget_policies_user_updated (user_id, updated_at DESC),
    CONSTRAINT fk_ai_budget_policies_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_ai_budget_warning CHECK (warning_threshold_percent BETWEEN 1 AND 100),
    CONSTRAINT chk_ai_budget_currency CHECK (currency REGEXP '^[A-Z]{3}$'),
    CONSTRAINT chk_ai_budget_cost CHECK ((daily_cost_limit IS NULL OR daily_cost_limit >= 0) AND (monthly_cost_limit IS NULL OR monthly_cost_limit >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE operational_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT 'USER',
    run_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    batch_id VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    metrics_json JSON NOT NULL,
    summary_safe VARCHAR(1000) NOT NULL,
    artifact_manifest_path VARCHAR(500) NULL,
    artifact_sha256 CHAR(64) NULL,
    rpo_seconds BIGINT UNSIGNED NULL,
    rto_seconds BIGINT UNSIGNED NULL,
    error_code VARCHAR(80) NULL,
    trace_id VARCHAR(64) NULL,
    created_by VARCHAR(24) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_operational_runs_public_id (public_id),
    UNIQUE KEY uk_operational_runs_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_operational_runs_batch_type (user_id, batch_id, run_type),
    KEY idx_operational_runs_user_time (user_id, created_at DESC),
    KEY idx_operational_runs_type_status (run_type, status, finished_at DESC),
    CONSTRAINT fk_operational_runs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_operational_runs_scope CHECK (scope IN ('USER','SYSTEM')),
    CONSTRAINT chk_operational_runs_type CHECK (run_type IN ('BACKUP','RESTORE_DRILL','DEPENDENCY_SCAN','SECRET_SCAN','LICENSE_SCAN','CONTAINER_SCAN','LOAD_TEST')),
    CONSTRAINT chk_operational_runs_status CHECK (status IN ('RUNNING','SUCCEEDED','FAILED','PARTIAL')),
    CONSTRAINT chk_operational_runs_creator CHECK (created_by IN ('USER','SCRIPT')),
    CONSTRAINT chk_operational_runs_artifact_hash CHECK (artifact_sha256 IS NULL OR artifact_sha256 REGEXP '^[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
