CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(254) NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NULL,
    avatar_url VARCHAR(500) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_public_id (public_id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email),
    KEY idx_users_status (status, deleted_at),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE refresh_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(43) NOT NULL,
    family_id CHAR(26) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    replaced_by_hash CHAR(43) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_refresh_tokens_public_id (public_id),
    UNIQUE KEY uk_refresh_tokens_hash (token_hash),
    KEY idx_refresh_tokens_user_expiry (user_id, expires_at),
    KEY idx_refresh_tokens_family (family_id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(64) NULL,
    trace_id VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_audit_logs_public_id (public_id),
    KEY idx_audit_logs_user_time (user_id, created_at DESC),
    KEY idx_audit_logs_resource (resource_type, resource_id),
    KEY idx_audit_logs_trace (trace_id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE candidate_profiles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    full_name VARCHAR(100) NULL,
    headline VARCHAR(160) NULL,
    phone VARCHAR(32) NULL,
    email VARCHAR(254) NULL,
    current_city VARCHAR(100) NULL,
    target_cities_json JSON NOT NULL,
    graduation_year SMALLINT UNSIGNED NULL,
    highest_education VARCHAR(40) NULL,
    school VARCHAR(160) NULL,
    major VARCHAR(160) NULL,
    years_of_experience DECIMAL(4,1) NULL,
    job_status VARCHAR(40) NULL,
    github_url VARCHAR(500) NULL,
    personal_website VARCHAR(500) NULL,
    summary TEXT NULL,
    target_roles_json JSON NOT NULL,
    target_industries_json JSON NOT NULL,
    target_company_types_json JSON NOT NULL,
    target_salary_min DECIMAL(12,2) NULL,
    target_salary_max DECIMAL(12,2) NULL,
    salary_currency CHAR(3) NOT NULL DEFAULT 'CNY',
    accept_remote TINYINT(1) NOT NULL DEFAULT 0,
    accept_relocation TINYINT(1) NOT NULL DEFAULT 0,
    profile_completeness TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_user_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN user_id ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_candidate_profiles_public_id (public_id),
    UNIQUE KEY uk_candidate_profiles_active_user (active_user_id),
    KEY idx_candidate_profiles_user (user_id, deleted_at),
    CONSTRAINT fk_candidate_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_candidate_profiles_completeness CHECK (profile_completeness BETWEEN 0 AND 100),
    CONSTRAINT chk_candidate_profiles_salary CHECK (target_salary_min IS NULL OR target_salary_max IS NULL OR target_salary_min <= target_salary_max)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE educations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    school VARCHAR(160) NOT NULL,
    degree VARCHAR(40) NOT NULL,
    major VARCHAR(160) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    graduation_year SMALLINT UNSIGNED NULL,
    description TEXT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_educations_public_id (public_id),
    KEY idx_educations_user_sort (user_id, deleted_at, sort_order),
    CONSTRAINT fk_educations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_educations_dates CHECK (end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE experiences (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    company_name VARCHAR(200) NOT NULL,
    role VARCHAR(160) NOT NULL,
    employment_type VARCHAR(24) NOT NULL,
    location VARCHAR(160) NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    currently_working TINYINT(1) NOT NULL DEFAULT 0,
    description TEXT NULL,
    responsibilities TEXT NULL,
    achievements TEXT NULL,
    technologies_json JSON NOT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_experiences_public_id (public_id),
    KEY idx_experiences_user_sort (user_id, deleted_at, sort_order),
    CONSTRAINT fk_experiences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_experiences_type CHECK (employment_type IN ('INTERNSHIP', 'FULL_TIME', 'PART_TIME', 'OTHER')),
    CONSTRAINT chk_experiences_dates CHECK (end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(200) NOT NULL,
    role VARCHAR(160) NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    description TEXT NOT NULL,
    background TEXT NULL,
    responsibilities TEXT NULL,
    achievements TEXT NULL,
    technologies_json JSON NOT NULL,
    repo_url VARCHAR(500) NULL,
    demo_url VARCHAR(500) NULL,
    featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_projects_public_id (public_id),
    KEY idx_projects_user_featured (user_id, deleted_at, featured, sort_order),
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_projects_dates CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    canonical_name VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    category VARCHAR(32) NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_skills_public_id (public_id),
    UNIQUE KEY uk_skills_canonical_name (canonical_name),
    KEY idx_skills_category_name (category, display_name),
    CONSTRAINT chk_skills_category CHECK (category IN ('LANGUAGE','FRAMEWORK','DATABASE','CACHE','MESSAGE_QUEUE','DEVOPS','CLOUD','AI','FRONTEND','TOOL','OTHER')),
    CONSTRAINT chk_skills_status CHECK (status IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE candidate_skills (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    candidate_profile_id BIGINT UNSIGNED NOT NULL,
    skill_id BIGINT UNSIGNED NOT NULL,
    proficiency TINYINT UNSIGNED NOT NULL,
    years DECIMAL(4,1) NULL,
    last_used_at DATE NULL,
    source VARCHAR(80) NOT NULL DEFAULT 'USER',
    primary_skill TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_candidate_skills_public_id (public_id),
    UNIQUE KEY uk_candidate_skills_active (user_id, skill_id, active_marker),
    KEY idx_candidate_skills_user_rank (user_id, deleted_at, primary_skill, proficiency),
    CONSTRAINT fk_candidate_skills_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_candidate_skills_profile FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profiles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_candidate_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (id) ON DELETE RESTRICT,
    CONSTRAINT chk_candidate_skills_proficiency CHECK (proficiency BETWEEN 0 AND 100),
    CONSTRAINT chk_candidate_skills_years CHECK (years IS NULL OR years BETWEEN 0 AND 80)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resumes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    target_role VARCHAR(160) NULL,
    master TINYINT(1) NOT NULL DEFAULT 0,
    default_resume TINYINT(1) NOT NULL DEFAULT 0,
    description TEXT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    current_version_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_master_user_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN master = 1 AND status = 'ACTIVE' AND deleted_at IS NULL THEN user_id ELSE NULL END) STORED,
    active_default_user_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN default_resume = 1 AND status = 'ACTIVE' AND deleted_at IS NULL THEN user_id ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resumes_public_id (public_id),
    UNIQUE KEY uk_resumes_active_master (active_master_user_id),
    UNIQUE KEY uk_resumes_active_default (active_default_user_id),
    KEY idx_resumes_user_status (user_id, deleted_at, status),
    KEY idx_resumes_current_version (current_version_id),
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_resumes_status CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resume_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    resume_id BIGINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    version_name VARCHAR(160) NOT NULL,
    content_json JSON NOT NULL,
    rendered_text MEDIUMTEXT NULL,
    source_type VARCHAR(24) NOT NULL,
    created_by VARCHAR(40) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    content_hash CHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resume_versions_public_id (public_id),
    UNIQUE KEY uk_resume_versions_number (resume_id, version_number),
    KEY idx_resume_versions_resume_time (resume_id, created_at DESC),
    CONSTRAINT fk_resume_versions_resume FOREIGN KEY (resume_id) REFERENCES resumes (id) ON DELETE RESTRICT,
    CONSTRAINT chk_resume_versions_source CHECK (source_type IN ('MANUAL','IMPORT','AI'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE resumes
    ADD CONSTRAINT fk_resumes_current_version FOREIGN KEY (current_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT;

CREATE TABLE resume_sections (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    resume_version_id BIGINT UNSIGNED NOT NULL,
    section_type VARCHAR(32) NOT NULL,
    content_json JSON NOT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resume_sections_public_id (public_id),
    UNIQUE KEY uk_resume_sections_type (resume_version_id, section_type),
    KEY idx_resume_sections_version_sort (resume_version_id, sort_order),
    CONSTRAINT fk_resume_sections_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_resume_sections_type CHECK (section_type IN ('BASIC_INFO','SUMMARY','EDUCATION','SKILLS','EXPERIENCE','PROJECTS','CERTIFICATIONS','AWARDS','OPEN_SOURCE','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO skills (public_id, canonical_name, display_name, category, description, status, created_at, updated_at, version) VALUES
('01K45X9J9B0000000000000001', 'java', 'Java', 'LANGUAGE', 'Java programming language', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000002', 'spring', 'Spring', 'FRAMEWORK', 'Spring Framework', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000003', 'spring_boot', 'Spring Boot', 'FRAMEWORK', 'Spring Boot application framework', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000004', 'mysql', 'MySQL', 'DATABASE', 'MySQL relational database', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000005', 'redis', 'Redis', 'CACHE', 'Redis data store and cache', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000006', 'rabbitmq', 'RabbitMQ', 'MESSAGE_QUEUE', 'RabbitMQ message broker', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000007', 'kafka', 'Kafka', 'MESSAGE_QUEUE', 'Apache Kafka event streaming', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000008', 'spring_cloud', 'Spring Cloud', 'FRAMEWORK', 'Spring Cloud microservice toolkit', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B0000000000000009', 'docker', 'Docker', 'DEVOPS', 'Container build and runtime', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000A', 'linux', 'Linux', 'DEVOPS', 'Linux operating system', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000B', 'git', 'Git', 'TOOL', 'Distributed version control', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000C', 'python', 'Python', 'LANGUAGE', 'Python programming language', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000D', 'langgraph', 'LangGraph', 'AI', 'Agent workflow framework', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000E', 'rag', 'RAG', 'AI', 'Retrieval augmented generation', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000F', 'milvus', 'Milvus', 'AI', 'Vector database', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000G', 'bge_m3', 'BGE-M3', 'AI', 'Multilingual embedding model', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000H', 'vue_3', 'Vue 3', 'FRONTEND', 'Vue 3 frontend framework', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
('01K45X9J9B000000000000000J', 'javascript', 'JavaScript', 'LANGUAGE', 'JavaScript language', 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0);
