CREATE TABLE job_recommendations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    latest_match_id BIGINT UNSIGNED NULL,
    recommendation_status VARCHAR(24) NOT NULL,
    favorite TINYINT(1) NOT NULL DEFAULT 0,
    rank_score DECIMAL(5,2) NULL,
    rank_version VARCHAR(40) NOT NULL DEFAULT 'recommendation-v1',
    rank_basis_json JSON NOT NULL,
    ignored_reason VARCHAR(500) NULL,
    ignored_at DATETIME(3) NULL,
    last_evaluated_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_job_recommendations_public_id (public_id),
    UNIQUE KEY uk_job_recommendations_active (user_id, job_id, active_marker),
    KEY idx_job_recommendations_list (user_id, recommendation_status, rank_score DESC, id DESC),
    KEY idx_job_recommendations_favorite (user_id, favorite, updated_at DESC, id DESC),
    KEY idx_job_recommendations_match (latest_match_id),
    CONSTRAINT fk_job_recommendations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_recommendations_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_recommendations_match FOREIGN KEY (latest_match_id) REFERENCES job_matches (id) ON DELETE RESTRICT,
    CONSTRAINT chk_job_recommendations_status CHECK (recommendation_status IN ('UNEVALUATED','READY','MATCH_FAILED','IGNORED')),
    CONSTRAINT chk_job_recommendations_favorite CHECK (favorite IN (0, 1)),
    CONSTRAINT chk_job_recommendations_rank CHECK (rank_score IS NULL OR rank_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recommendation_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    recommendation_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    job_match_id BIGINT UNSIGNED NULL,
    event_type VARCHAR(24) NOT NULL,
    reason VARCHAR(500) NULL,
    previous_state_json JSON NOT NULL,
    current_state_json JSON NOT NULL,
    feature_snapshot_json JSON NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_events_public_id (public_id),
    KEY idx_recommendation_events_history (user_id, recommendation_id, occurred_at DESC, id DESC),
    KEY idx_recommendation_events_job (user_id, job_id, occurred_at DESC),
    CONSTRAINT fk_recommendation_events_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_events_recommendation FOREIGN KEY (recommendation_id) REFERENCES job_recommendations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_events_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_events_match FOREIGN KEY (job_match_id) REFERENCES job_matches (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recommendation_events_type CHECK (event_type IN ('FAVORITE','UNFAVORITE','IGNORE','RESTORE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recommendation_refresh_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    criteria_json JSON NOT NULL,
    force_run TINYINT(1) NOT NULL DEFAULT 0,
    total_count INT UNSIGNED NOT NULL DEFAULT 0,
    submitted_count INT UNSIGNED NOT NULL DEFAULT 0,
    reused_count INT UNSIGNED NOT NULL DEFAULT 0,
    succeeded_count INT UNSIGNED NOT NULL DEFAULT 0,
    failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    error_message_safe VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_refresh_public_id (public_id),
    UNIQUE KEY uk_recommendation_refresh_idempotency (user_id, idempotency_key),
    KEY idx_recommendation_refresh_status (user_id, status, updated_at DESC, id DESC),
    CONSTRAINT fk_recommendation_refresh_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recommendation_refresh_status CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','PARTIAL_SUCCESS','FAILED')),
    CONSTRAINT chk_recommendation_refresh_force CHECK (force_run IN (0, 1)),
    CONSTRAINT chk_recommendation_refresh_counts CHECK (
        submitted_count <= total_count AND reused_count <= total_count AND
        succeeded_count <= total_count AND failed_count <= total_count
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recommendation_refresh_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    refresh_run_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    match_run_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    reused TINYINT(1) NOT NULL DEFAULT 0,
    error_message_safe VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recommendation_refresh_items_public_id (public_id),
    UNIQUE KEY uk_recommendation_refresh_items_job (refresh_run_id, job_id),
    KEY idx_recommendation_refresh_items_status (refresh_run_id, status, id),
    KEY idx_recommendation_refresh_items_match (match_run_id),
    CONSTRAINT fk_recommendation_refresh_items_run FOREIGN KEY (refresh_run_id) REFERENCES recommendation_refresh_runs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_refresh_items_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_refresh_items_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_refresh_items_match_run FOREIGN KEY (match_run_id) REFERENCES match_runs (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recommendation_refresh_items_status CHECK (status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','DEAD')),
    CONSTRAINT chk_recommendation_refresh_items_reused CHECK (reused IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE analytics_daily (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    metric_date DATE NOT NULL,
    dimension_type VARCHAR(40) NOT NULL,
    dimension_key VARCHAR(160) NOT NULL,
    job_count INT UNSIGNED NOT NULL DEFAULT 0,
    evaluated_count INT UNSIGNED NOT NULL DEFAULT 0,
    high_match_count INT UNSIGNED NOT NULL DEFAULT 0,
    favorite_count INT UNSIGNED NOT NULL DEFAULT 0,
    ignored_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_analytics_daily_public_id (public_id),
    UNIQUE KEY uk_analytics_daily_dimension (user_id, metric_date, dimension_type, dimension_key, active_marker),
    KEY idx_analytics_daily_range (user_id, metric_date, dimension_type),
    CONSTRAINT fk_analytics_daily_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_analytics_daily_dimension CHECK (dimension_type IN ('OVERALL','SOURCE','CITY','LEVEL','RECOMMENDATION_STATUS'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
