CREATE TABLE platform_policies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    platform VARCHAR(80) NOT NULL,
    collection_mode VARCHAR(32) NOT NULL DEFAULT 'MANUAL_ONLY',
    application_mode VARCHAR(32) NOT NULL DEFAULT 'MANUAL_ONLY',
    requires_final_confirmation TINYINT(1) NOT NULL DEFAULT 1,
    rate_limit_json JSON NOT NULL,
    policy_source_url VARCHAR(1000) NULL,
    reviewed_at DATETIME(3) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_platform_policies_public_id (public_id),
    UNIQUE KEY uk_platform_policies_active (platform, active_marker),
    CONSTRAINT chk_platform_policies_collection CHECK (collection_mode IN ('MANUAL_ONLY','VISIBLE_PAGE_ONLY')),
    CONSTRAINT chk_platform_policies_application CHECK (application_mode IN ('MANUAL_ONLY','ASSIST_ALLOWED','AUTHORIZED_AUTOMATION')),
    CONSTRAINT chk_platform_policies_confirmation CHECK (requires_final_confirmation IN (0, 1)),
    CONSTRAINT chk_platform_policies_status CHECK (status IN ('ACTIVE','STALE','DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recruiters (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED NULL,
    name VARCHAR(120) NOT NULL,
    position VARCHAR(160) NULL,
    platform VARCHAR(80) NULL,
    platform_recruiter_id VARCHAR(160) NULL,
    contact_masked VARCHAR(160) NULL,
    email VARCHAR(254) NULL,
    phone VARCHAR(40) NULL,
    last_contact_at DATETIME(3) NULL,
    next_follow_up_at DATETIME(3) NULL,
    communication_status VARCHAR(32) NOT NULL DEFAULT 'NEW',
    notes VARCHAR(2000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_platform_key VARCHAR(260) GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND platform IS NOT NULL AND platform_recruiter_id IS NOT NULL THEN CONCAT(user_id, ':', platform, ':', platform_recruiter_id) ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recruiters_public_id (public_id),
    UNIQUE KEY uk_recruiters_platform_identity (active_platform_key),
    KEY idx_recruiters_follow_up (user_id, communication_status, next_follow_up_at),
    KEY idx_recruiters_company (company_id),
    CONSTRAINT fk_recruiters_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recruiters_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recruiters_status CHECK (communication_status IN ('NEW','CONTACTED','REPLIED','FOLLOW_UP','CLOSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_queue_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    job_match_id BIGINT UNSIGNED NULL,
    resume_version_id BIGINT UNSIGNED NOT NULL,
    greeting_reference VARCHAR(160) NULL,
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority TINYINT UNSIGNED NOT NULL DEFAULT 50,
    scheduled_at DATETIME(3) NULL,
    approved_at DATETIME(3) NULL,
    approved_by BIGINT UNSIGNED NULL,
    prepared_at DATETIME(3) NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    last_error_code VARCHAR(80) NULL,
    last_error_message VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status IN ('WAITING','READY','NEED_REVIEW','APPROVED','PREPARED','BLOCKED') THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_application_queue_public_id (public_id),
    UNIQUE KEY uk_application_queue_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_application_queue_active_job (user_id, job_id, active_marker),
    KEY idx_application_queue_list (user_id, status, priority DESC, scheduled_at, id),
    KEY idx_application_queue_match (job_match_id),
    KEY idx_application_queue_resume (resume_version_id),
    CONSTRAINT fk_application_queue_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_queue_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_queue_match FOREIGN KEY (job_match_id) REFERENCES job_matches (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_queue_resume FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_queue_approver FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_application_queue_mode CHECK (mode IN ('MANUAL','ASSIST','AUTHORIZED_AUTOMATION')),
    CONSTRAINT chk_application_queue_status CHECK (status IN ('WAITING','READY','NEED_REVIEW','APPROVED','PREPARED','SUCCESS','FAILED','SKIPPED','BLOCKED')),
    CONSTRAINT chk_application_queue_priority CHECK (priority BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE applications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    job_source_id BIGINT UNSIGNED NULL,
    resume_version_id BIGINT UNSIGNED NOT NULL,
    recruiter_id BIGINT UNSIGNED NULL,
    queue_item_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL,
    application_mode VARCHAR(32) NOT NULL,
    applied_at DATETIME(3) NOT NULL,
    last_status_at DATETIME(3) NOT NULL,
    external_application_id VARCHAR(200) NULL,
    source_url_snapshot VARCHAR(1000) NULL,
    notes VARCHAR(4000) NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status NOT IN ('REJECTED','WITHDRAWN','CLOSED') THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_applications_public_id (public_id),
    UNIQUE KEY uk_applications_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_applications_queue (queue_item_id),
    UNIQUE KEY uk_applications_active_job (user_id, job_id, active_marker),
    KEY idx_applications_crm (user_id, status, last_status_at DESC, id DESC),
    KEY idx_applications_recruiter (recruiter_id),
    CONSTRAINT fk_applications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_job_source FOREIGN KEY (job_source_id) REFERENCES job_sources (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_resume FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_applications_queue FOREIGN KEY (queue_item_id) REFERENCES application_queue_items (id) ON DELETE RESTRICT,
    CONSTRAINT chk_applications_status CHECK (status IN ('APPLIED','VIEWED','REPLIED','WRITTEN_TEST','INTERVIEW_1','INTERVIEW_2','INTERVIEW_3','HR_INTERVIEW','OFFER','REJECTED','WITHDRAWN','CLOSED')),
    CONSTRAINT chk_applications_mode CHECK (application_mode IN ('MANUAL','ASSIST','AUTHORIZED_AUTOMATION'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    application_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    source VARCHAR(32) NOT NULL,
    actor_user_id BIGINT UNSIGNED NULL,
    note VARCHAR(2000) NULL,
    evidence_json JSON NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_application_logs_public_id (public_id),
    KEY idx_application_logs_timeline (user_id, application_id, occurred_at, id),
    CONSTRAINT fk_application_logs_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_application_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_application_logs_source CHECK (source IN ('USER','PLATFORM_IMPORT','AUTOMATION','SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE recruiter_interactions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    recruiter_id BIGINT UNSIGNED NOT NULL,
    application_id BIGINT UNSIGNED NULL,
    channel VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    summary VARCHAR(2000) NOT NULL,
    follow_up_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_recruiter_interactions_public_id (public_id),
    KEY idx_recruiter_interactions_timeline (user_id, recruiter_id, occurred_at DESC, id DESC),
    KEY idx_recruiter_interactions_application (application_id),
    CONSTRAINT fk_recruiter_interactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recruiter_interactions_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recruiter_interactions_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recruiter_interactions_channel CHECK (channel IN ('PLATFORM','EMAIL','PHONE','WECHAT','SMS','OTHER')),
    CONSTRAINT chk_recruiter_interactions_direction CHECK (direction IN ('OUTBOUND','INBOUND','NOTE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE analytics_daily
    ADD COLUMN queued_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER ignored_count,
    ADD COLUMN applied_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER queued_count,
    ADD COLUMN viewed_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER applied_count,
    ADD COLUMN replied_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER viewed_count,
    ADD COLUMN written_test_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER replied_count,
    ADD COLUMN interview_stage_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER written_test_count,
    ADD COLUMN offer_stage_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER interview_stage_count,
    ADD COLUMN terminal_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER offer_stage_count;

INSERT INTO platform_policies (
    public_id, platform, collection_mode, application_mode, requires_final_confirmation,
    rate_limit_json, policy_source_url, reviewed_at, status, created_at, updated_at, version
) VALUES
    ('01K5PHASE5MANUALDEFAULT001', 'MANUAL', 'MANUAL_ONLY', 'ASSIST_ALLOWED', 1, JSON_OBJECT(), NULL, UTC_TIMESTAMP(3), 'ACTIVE', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0);
