CREATE TABLE prompt_templates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    template_key VARCHAR(80) NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    system_prompt MEDIUMTEXT NOT NULL,
    input_schema_version VARCHAR(80) NOT NULL,
    output_schema_version VARCHAR(80) NOT NULL,
    prompt_hash CHAR(64) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 0,
    created_by VARCHAR(40) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_template_key VARCHAR(80) GENERATED ALWAYS AS
        (CASE WHEN active = 1 AND deleted_at IS NULL THEN template_key ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_prompt_templates_public_id (public_id),
    UNIQUE KEY uk_prompt_templates_key_version (template_key, version_no),
    UNIQUE KEY uk_prompt_templates_active (active_template_key),
    KEY idx_prompt_templates_key_time (template_key, created_at DESC),
    CONSTRAINT chk_prompt_templates_active CHECK (active IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE candidate_evidence_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    evidence_key VARCHAR(240) NOT NULL,
    evidence_type VARCHAR(40) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_public_id CHAR(26) NOT NULL,
    field_path VARCHAR(160) NOT NULL,
    value_json JSON NOT NULL,
    normalized_text TEXT NOT NULL,
    content_hash CHAR(64) NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_candidate_evidence_public_id (public_id),
    UNIQUE KEY uk_candidate_evidence_version (user_id, evidence_key, version_no),
    UNIQUE KEY uk_candidate_evidence_hash (user_id, evidence_key, content_hash),
    KEY idx_candidate_evidence_user_type (user_id, evidence_type, created_at DESC),
    CONSTRAINT fk_candidate_evidence_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_candidate_evidence_type CHECK (evidence_type IN
        ('PROFILE','EDUCATION','EXPERIENCE','PROJECT','SKILL','RESUME_SECTION'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE ai_call_logs
    ADD COLUMN prompt_template_id BIGINT UNSIGNED NULL AFTER task_type,
    ADD KEY idx_ai_call_logs_prompt (prompt_template_id),
    ADD CONSTRAINT fk_ai_call_logs_prompt FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates (id) ON DELETE RESTRICT;

ALTER TABLE resume_versions
    ADD COLUMN parent_version_id BIGINT UNSIGNED NULL AFTER resume_id,
    ADD COLUMN tailored_for_job_id BIGINT UNSIGNED NULL AFTER content_hash,
    ADD COLUMN prompt_template_id BIGINT UNSIGNED NULL AFTER tailored_for_job_id,
    ADD COLUMN ai_call_id BIGINT UNSIGNED NULL AFTER prompt_template_id,
    ADD COLUMN model_name VARCHAR(160) NULL AFTER ai_call_id,
    ADD COLUMN truth_check_status VARCHAR(32) NULL AFTER model_name,
    ADD KEY idx_resume_versions_parent (parent_version_id),
    ADD KEY idx_resume_versions_tailored_job (tailored_for_job_id, created_at DESC),
    ADD KEY idx_resume_versions_prompt (prompt_template_id),
    ADD KEY idx_resume_versions_ai_call (ai_call_id),
    ADD CONSTRAINT fk_resume_versions_parent FOREIGN KEY (parent_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_resume_versions_tailored_job FOREIGN KEY (tailored_for_job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_resume_versions_prompt FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates (id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_resume_versions_ai_call FOREIGN KEY (ai_call_id) REFERENCES ai_call_logs (id) ON DELETE RESTRICT,
    ADD CONSTRAINT chk_resume_versions_truth CHECK
        (truth_check_status IS NULL OR truth_check_status IN ('VERIFIED','FAILED_TRUTH_CHECK'));

CREATE TABLE resume_tailor_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    base_resume_version_id BIGINT UNSIGNED NOT NULL,
    target_resume_id BIGINT UNSIGNED NULL,
    prompt_template_id BIGINT UNSIGNED NOT NULL,
    ai_call_id BIGINT UNSIGNED NULL,
    approved_resume_version_id BIGINT UNSIGNED NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    input_hash CHAR(64) NOT NULL,
    strategy VARCHAR(40) NOT NULL,
    status VARCHAR(32) NOT NULL,
    execution_mode VARCHAR(32) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    model_name VARCHAR(160) NULL,
    truth_check_status VARCHAR(32) NOT NULL,
    evidence_snapshot_hash CHAR(64) NOT NULL,
    proposed_content_json JSON NOT NULL,
    proposed_rendered_text MEDIUMTEXT NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    started_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    approved_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resume_tailor_runs_public_id (public_id),
    UNIQUE KEY uk_resume_tailor_runs_idempotency (user_id, idempotency_key),
    KEY idx_resume_tailor_runs_user_time (user_id, created_at DESC),
    KEY idx_resume_tailor_runs_job_time (user_id, job_id, created_at DESC),
    KEY idx_resume_tailor_runs_status (status, created_at),
    CONSTRAINT fk_resume_tailor_runs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_base_version FOREIGN KEY (base_resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_target_resume FOREIGN KEY (target_resume_id) REFERENCES resumes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_prompt FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_ai_call FOREIGN KEY (ai_call_id) REFERENCES ai_call_logs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_tailor_runs_approved_version FOREIGN KEY (approved_resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_resume_tailor_runs_status CHECK (status IN ('READY','FAILED_TRUTH_CHECK','FAILED','APPROVED')),
    CONSTRAINT chk_resume_tailor_runs_truth CHECK (truth_check_status IN ('VERIFIED','FAILED_TRUTH_CHECK')),
    CONSTRAINT chk_resume_tailor_runs_mode CHECK (execution_mode IN ('RULES_ONLY','LLM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resume_tailor_changes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    tailor_run_id BIGINT UNSIGNED NOT NULL,
    section_type VARCHAR(32) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    before_text TEXT NULL,
    after_text TEXT NOT NULL,
    reason_text VARCHAR(1000) NOT NULL,
    evidence_refs_json JSON NOT NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resume_tailor_changes_public_id (public_id),
    KEY idx_resume_tailor_changes_run_sort (tailor_run_id, sort_order, id),
    CONSTRAINT fk_resume_tailor_changes_run FOREIGN KEY (tailor_run_id) REFERENCES resume_tailor_runs (id) ON DELETE RESTRICT,
    CONSTRAINT chk_resume_tailor_changes_section CHECK (section_type IN
        ('BASIC_INFO','SUMMARY','EDUCATION','SKILLS','EXPERIENCE','PROJECTS','CERTIFICATIONS','AWARDS','OPEN_SOURCE','OTHER')),
    CONSTRAINT chk_resume_tailor_changes_operation CHECK (operation IN ('SELECT','REORDER','REWRITE','COMPRESS','ATS_KEYWORD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE communication_drafts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    application_id BIGINT UNSIGNED NULL,
    resume_version_id BIGINT UNSIGNED NULL,
    recruiter_id BIGINT UNSIGNED NULL,
    channel VARCHAR(24) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    char_count INT UNSIGNED NOT NULL,
    evidence_refs_json JSON NOT NULL,
    prompt_template_id BIGINT UNSIGNED NOT NULL,
    ai_call_id BIGINT UNSIGNED NULL,
    execution_mode VARCHAR(32) NOT NULL,
    truth_check_status VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    approved_at DATETIME(3) NULL,
    used_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_communication_drafts_public_id (public_id),
    UNIQUE KEY uk_communication_drafts_idempotency (user_id, idempotency_key),
    KEY idx_communication_drafts_user_time (user_id, created_at DESC),
    KEY idx_communication_drafts_job (user_id, job_id, created_at DESC),
    KEY idx_communication_drafts_status (user_id, status, updated_at DESC),
    CONSTRAINT fk_communication_drafts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_recruiter FOREIGN KEY (recruiter_id) REFERENCES recruiters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_prompt FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_communication_drafts_ai_call FOREIGN KEY (ai_call_id) REFERENCES ai_call_logs (id) ON DELETE RESTRICT,
    CONSTRAINT chk_communication_drafts_channel CHECK (channel IN
        ('BOSS','LIEPIN','EMAIL','WECHAT','THANK_YOU','FOLLOW_UP','OFFER')),
    CONSTRAINT chk_communication_drafts_status CHECK (status IN ('DRAFT','APPROVED','USED','ARCHIVED')),
    CONSTRAINT chk_communication_drafts_truth CHECK (truth_check_status IN ('VERIFIED','FAILED_TRUTH_CHECK')),
    CONSTRAINT chk_communication_drafts_mode CHECK (execution_mode IN ('RULES_ONLY','LLM')),
    CONSTRAINT chk_communication_drafts_char_count CHECK (char_count > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resume_version_metrics (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    resume_version_id BIGINT UNSIGNED NOT NULL,
    queue_use_count INT UNSIGNED NOT NULL DEFAULT 0,
    application_count INT UNSIGNED NOT NULL DEFAULT 0,
    reply_count INT UNSIGNED NOT NULL DEFAULT 0,
    interview_count INT UNSIGNED NOT NULL DEFAULT 0,
    offer_count INT UNSIGNED NOT NULL DEFAULT 0,
    calculated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_version_id BIGINT UNSIGNED GENERATED ALWAYS AS
        (CASE WHEN deleted_at IS NULL THEN resume_version_id ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_resume_version_metrics_public_id (public_id),
    UNIQUE KEY uk_resume_version_metrics_active (active_version_id),
    KEY idx_resume_version_metrics_user (user_id, calculated_at DESC),
    CONSTRAINT fk_resume_version_metrics_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resume_version_metrics_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO prompt_templates
    (public_id, template_key, version_no, display_name, system_prompt,
     input_schema_version, output_schema_version, prompt_hash, active, created_by,
     created_at, updated_at, version)
VALUES
    ('01M1G000000000000000000001', 'RESUME_TAILOR', 1, 'Evidence-bound Resume Tailor v1',
     'Only select, reorder, compress or rewrite facts referenced by evidenceRefs. Never invent candidate facts.',
     'resume-tailor-request-v1', 'resume-tailor-response-v1',
     SHA2('Only select, reorder, compress or rewrite facts referenced by evidenceRefs. Never invent candidate facts.', 256),
     1, 'SYSTEM', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0),
    ('01M1G000000000000000000002', 'COMMUNICATION_DRAFT', 1, 'Evidence-bound Communication Draft v1',
     'Create a draft only. Use candidate evidence, never claim unprovided facts, and never send external messages.',
     'communication-draft-request-v1', 'communication-draft-response-v1',
     SHA2('Create a draft only. Use candidate evidence, never claim unprovided facts, and never send external messages.', 256),
     1, 'SYSTEM', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 0);
