CREATE TABLE extension_pairing_codes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    code_hash CHAR(64) NOT NULL,
    scopes_json JSON NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    used_at DATETIME(3) NULL,
    used_by_device_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_extension_pairing_codes_public_id (public_id),
    UNIQUE KEY uk_extension_pairing_codes_hash (code_hash),
    KEY idx_extension_pairing_codes_user_time (user_id, created_at DESC),
    KEY idx_extension_pairing_codes_expiry (expires_at, used_at),
    CONSTRAINT fk_extension_pairing_codes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE extension_devices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    device_name VARCHAR(120) NOT NULL,
    browser_name VARCHAR(80) NOT NULL,
    extension_id VARCHAR(80) NOT NULL,
    extension_version VARCHAR(40) NOT NULL,
    scopes_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL,
    token_version INT UNSIGNED NOT NULL DEFAULT 1,
    paired_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_extension_devices_public_id (public_id),
    KEY idx_extension_devices_user_status (user_id, status, created_at DESC),
    CONSTRAINT fk_extension_devices_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_extension_devices_status CHECK (status IN ('ACTIVE','REVOKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE extension_pairing_codes
    ADD CONSTRAINT fk_extension_pairing_codes_device FOREIGN KEY (used_by_device_id) REFERENCES extension_devices (id) ON DELETE RESTRICT;

CREATE TABLE extension_refresh_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    device_id BIGINT UNSIGNED NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    replaced_by_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_extension_refresh_public_id (public_id),
    UNIQUE KEY uk_extension_refresh_hash (token_hash),
    KEY idx_extension_refresh_device (device_id, expires_at DESC),
    KEY idx_extension_refresh_user (user_id, created_at DESC),
    CONSTRAINT fk_extension_refresh_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_extension_refresh_device FOREIGN KEY (device_id) REFERENCES extension_devices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_extension_refresh_replacement FOREIGN KEY (replaced_by_id) REFERENCES extension_refresh_tokens (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    extension_device_id BIGINT UNSIGNED NULL,
    queue_item_id BIGINT UNSIGNED NOT NULL,
    platform_policy_id BIGINT UNSIGNED NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    task_token_hash CHAR(64) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    target_url VARCHAR(1000) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    externally_submitted TINYINT(1) NOT NULL DEFAULT 0,
    application_created TINYINT(1) NOT NULL DEFAULT 0,
    final_confirmation_required TINYINT(1) NOT NULL DEFAULT 1,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_tasks_public_id (public_id),
    UNIQUE KEY uk_automation_tasks_idempotency (user_id, idempotency_key),
    KEY idx_automation_tasks_user_time (user_id, created_at DESC),
    KEY idx_automation_tasks_status_time (status, created_at),
    CONSTRAINT fk_automation_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_tasks_device FOREIGN KEY (extension_device_id) REFERENCES extension_devices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_tasks_queue FOREIGN KEY (queue_item_id) REFERENCES application_queue_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_automation_tasks_policy FOREIGN KEY (platform_policy_id) REFERENCES platform_policies (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_tasks_type CHECK (task_type = 'ASSIST_PREPARE'),
    CONSTRAINT chk_automation_tasks_status CHECK (status IN ('PENDING','RUNNING','PREPARED','BLOCKED','FAILED','CANCELLED')),
    CONSTRAINT chk_automation_tasks_no_submit CHECK (externally_submitted = 0 AND application_created = 0 AND final_confirmation_required = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE automation_task_steps (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    sequence_no INT UNSIGNED NOT NULL,
    step_type VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    selector_hint VARCHAR(240) NULL,
    detail_json JSON NULL,
    occurred_at DATETIME(3) NOT NULL,
    trace_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_automation_task_steps_public_id (public_id),
    UNIQUE KEY uk_automation_task_steps_sequence (task_id, sequence_no),
    KEY idx_automation_task_steps_task_time (task_id, occurred_at),
    CONSTRAINT fk_automation_task_steps_task FOREIGN KEY (task_id) REFERENCES automation_tasks (id) ON DELETE RESTRICT,
    CONSTRAINT chk_automation_task_steps_type CHECK (step_type IN ('OPEN','CHECK','FILL','HANDOFF','BLOCKED','ERROR')),
    CONSTRAINT chk_automation_task_steps_status CHECK (status IN ('SUCCEEDED','SKIPPED','BLOCKED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
