CREATE TABLE interviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    application_id BIGINT UNSIGNED NULL,
    job_id BIGINT UNSIGNED NULL,
    company_id BIGINT UNSIGNED NULL,
    resume_version_id BIGINT UNSIGNED NULL,
    company_name_snapshot VARCHAR(200) NOT NULL,
    role_snapshot VARCHAR(200) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'SCHEDULED',
    result VARCHAR(24) NULL,
    timezone VARCHAR(64) NOT NULL,
    notes VARCHAR(4000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interviews_public_id (public_id),
    KEY idx_interviews_user_status_time (user_id, status, updated_at DESC, id DESC),
    KEY idx_interviews_application (application_id),
    KEY idx_interviews_job (job_id),
    CONSTRAINT fk_interviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interviews_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interviews_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interviews_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interviews_resume FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interviews_status CHECK (status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW')),
    CONSTRAINT chk_interviews_result CHECK (result IS NULL OR result IN ('PENDING','PASSED','FAILED','MIXED','WITHDRAWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_rounds (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    round_no INT UNSIGNED NOT NULL,
    round_type VARCHAR(32) NOT NULL,
    title VARCHAR(160) NOT NULL,
    scheduled_start_at DATETIME(3) NOT NULL,
    scheduled_end_at DATETIME(3) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    format VARCHAR(24) NOT NULL,
    meeting_link VARCHAR(1000) NULL,
    location VARCHAR(300) NULL,
    interviewer_name VARCHAR(160) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PLANNED',
    result VARCHAR(24) NULL,
    notes VARCHAR(4000) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_round_no INT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN round_no ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_rounds_public_id (public_id),
    UNIQUE KEY uk_interview_rounds_number (interview_id, active_round_no),
    KEY idx_interview_rounds_user_time (user_id, scheduled_start_at, status),
    KEY idx_interview_rounds_interview_time (interview_id, scheduled_start_at, id),
    CONSTRAINT fk_interview_rounds_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_rounds_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_rounds_order CHECK (round_no BETWEEN 1 AND 100),
    CONSTRAINT chk_interview_rounds_time CHECK (scheduled_end_at > scheduled_start_at),
    CONSTRAINT chk_interview_rounds_type CHECK (round_type IN ('PHONE_SCREEN','TECHNICAL','SYSTEM_DESIGN','BEHAVIORAL','HR','MANAGER','FINAL','OTHER')),
    CONSTRAINT chk_interview_rounds_format CHECK (format IN ('ONLINE','ONSITE','PHONE','OTHER')),
    CONSTRAINT chk_interview_rounds_status CHECK (status IN ('PLANNED','COMPLETED','CANCELLED')),
    CONSTRAINT chk_interview_rounds_result CHECK (result IS NULL OR result IN ('PENDING','PASSED','FAILED','MIXED','WITHDRAWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_questions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    round_id BIGINT UNSIGNED NOT NULL,
    source_type VARCHAR(24) NOT NULL,
    category VARCHAR(40) NOT NULL,
    difficulty VARCHAR(16) NOT NULL,
    question_text VARCHAR(4000) NOT NULL,
    purpose_text VARCHAR(1000) NULL,
    basis_text VARCHAR(2000) NULL,
    answer_framework MEDIUMTEXT NULL,
    suggested_follow_ups_json JSON NOT NULL,
    risk_notes VARCHAR(2000) NULL,
    evidence_refs_json JSON NOT NULL,
    prediction_key VARCHAR(120) NULL,
    request_hash CHAR(64) NULL,
    prompt_version VARCHAR(80) NULL,
    model_name VARCHAR(160) NULL,
    ai_call_id BIGINT UNSIGNED NULL,
    generated_at DATETIME(3) NULL,
    display_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_questions_public_id (public_id),
    UNIQUE KEY uk_interview_questions_prediction (user_id, round_id, prediction_key, display_order),
    KEY idx_interview_questions_round_source (round_id, source_type, display_order, id),
    KEY idx_interview_questions_user_time (user_id, created_at DESC),
    CONSTRAINT fk_interview_questions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_questions_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_questions_round FOREIGN KEY (round_id) REFERENCES interview_rounds (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_questions_ai_call FOREIGN KEY (ai_call_id) REFERENCES ai_call_logs (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_questions_source CHECK (source_type IN ('PREDICTED','ACTUAL','MANUAL')),
    CONSTRAINT chk_interview_questions_difficulty CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT chk_interview_questions_category CHECK (category IN ('TECHNICAL_FOUNDATION','PROJECT_DEEP_DIVE','SYSTEM_DESIGN','BEHAVIORAL','ROLE_RISK','FOLLOW_UP','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_answer_notes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    question_id BIGINT UNSIGNED NOT NULL,
    note_version INT UNSIGNED NOT NULL,
    answer_text MEDIUMTEXT NOT NULL,
    self_rating TINYINT UNSIGNED NULL,
    user_recorded_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_answer_notes_public_id (public_id),
    UNIQUE KEY uk_interview_answer_notes_version (question_id, note_version),
    KEY idx_interview_answer_notes_user_time (user_id, created_at DESC),
    CONSTRAINT fk_interview_answer_notes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_answer_notes_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_answer_notes_question FOREIGN KEY (question_id) REFERENCES interview_questions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_answer_notes_rating CHECK (self_rating IS NULL OR self_rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_reviews (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    review_version INT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    summary_text MEDIUMTEXT NOT NULL,
    source_type VARCHAR(24) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    model_name VARCHAR(160) NULL,
    ai_call_id BIGINT UNSIGNED NULL,
    evidence_refs_json JSON NOT NULL,
    generated_at DATETIME(3) NOT NULL,
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_reviews_public_id (public_id),
    UNIQUE KEY uk_interview_reviews_version (interview_id, review_version),
    UNIQUE KEY uk_interview_reviews_idempotency (user_id, idempotency_key),
    KEY idx_interview_reviews_user_time (user_id, generated_at DESC),
    CONSTRAINT fk_interview_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_reviews_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_reviews_ai_call FOREIGN KEY (ai_call_id) REFERENCES ai_call_logs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_reviews_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_reviews_status CHECK (status IN ('DRAFT','CONFIRMED')),
    CONSTRAINT chk_interview_reviews_source CHECK (source_type IN ('RULES_ONLY','LLM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_review_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    review_id BIGINT UNSIGNED NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    title VARCHAR(240) NOT NULL,
    description_text VARCHAR(4000) NOT NULL,
    severity VARCHAR(16) NULL,
    evidence_text VARCHAR(4000) NULL,
    evidence_refs_json JSON NOT NULL,
    recommended_actions_json JSON NOT NULL,
    display_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_review_items_public_id (public_id),
    KEY idx_interview_review_items_review (review_id, item_type, display_order, id),
    CONSTRAINT fk_interview_review_items_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_review_items_review FOREIGN KEY (review_id) REFERENCES interview_reviews (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_review_items_type CHECK (item_type IN ('STRENGTH','WEAKNESS','EXPRESSION_ISSUE','PROJECT_RISK','NEXT_ACTION','KNOWLEDGE_GAP')),
    CONSTRAINT chk_interview_review_items_severity CHECK (severity IS NULL OR severity IN ('LOW','MEDIUM','HIGH'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE knowledge_gaps (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    source_interview_id BIGINT UNSIGNED NOT NULL,
    source_review_id BIGINT UNSIGNED NOT NULL,
    source_review_item_id BIGINT UNSIGNED NULL,
    title VARCHAR(240) NOT NULL,
    category VARCHAR(80) NOT NULL,
    description_text VARCHAR(4000) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    evidence_json JSON NOT NULL,
    recommended_actions_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PROPOSED',
    confirmed_by BIGINT UNSIGNED NULL,
    confirmed_at DATETIME(3) NULL,
    resolved_at DATETIME(3) NULL,
    dismissed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_gaps_public_id (public_id),
    KEY idx_knowledge_gaps_user_status (user_id, status, severity, updated_at DESC),
    KEY idx_knowledge_gaps_review (source_review_id),
    CONSTRAINT fk_knowledge_gaps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gaps_interview FOREIGN KEY (source_interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gaps_review FOREIGN KEY (source_review_id) REFERENCES interview_reviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gaps_review_item FOREIGN KEY (source_review_item_id) REFERENCES interview_review_items (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gaps_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_knowledge_gaps_severity CHECK (severity IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT chk_knowledge_gaps_status CHECK (status IN ('PROPOSED','ACTIVE','RESOLVED','DISMISSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE knowledge_gap_evidence (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    knowledge_gap_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    review_id BIGINT UNSIGNED NOT NULL,
    question_id BIGINT UNSIGNED NULL,
    evidence_type VARCHAR(32) NOT NULL,
    evidence_text VARCHAR(4000) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_gap_evidence_public_id (public_id),
    KEY idx_knowledge_gap_evidence_gap (knowledge_gap_id, created_at, id),
    CONSTRAINT fk_knowledge_gap_evidence_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gap_evidence_gap FOREIGN KEY (knowledge_gap_id) REFERENCES knowledge_gaps (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gap_evidence_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gap_evidence_review FOREIGN KEY (review_id) REFERENCES interview_reviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_knowledge_gap_evidence_question FOREIGN KEY (question_id) REFERENCES interview_questions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_knowledge_gap_evidence_type CHECK (evidence_type IN ('ACTUAL_QUESTION','ANSWER_NOTE','USER_CONFIRMATION','AI_INFERENCE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE interview_reminders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    interview_id BIGINT UNSIGNED NOT NULL,
    round_id BIGINT UNSIGNED NULL,
    reminder_type VARCHAR(32) NOT NULL,
    title VARCHAR(240) NOT NULL,
    remind_at DATETIME(3) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    completed_at DATETIME(3) NULL,
    cancelled_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    round_dedup_id BIGINT UNSIGNED GENERATED ALWAYS AS (IFNULL(round_id, 0)) STORED,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status = 'PENDING' THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_interview_reminders_public_id (public_id),
    UNIQUE KEY uk_interview_reminders_active (interview_id, round_dedup_id, reminder_type, remind_at, active_marker),
    KEY idx_interview_reminders_user_due (user_id, status, remind_at, id),
    KEY idx_interview_reminders_interview (interview_id, status, remind_at),
    CONSTRAINT fk_interview_reminders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_reminders_interview FOREIGN KEY (interview_id) REFERENCES interviews (id) ON DELETE RESTRICT,
    CONSTRAINT fk_interview_reminders_round FOREIGN KEY (round_id) REFERENCES interview_rounds (id) ON DELETE RESTRICT,
    CONSTRAINT chk_interview_reminders_type CHECK (reminder_type IN ('PREPARE','START','REVIEW','CUSTOM')),
    CONSTRAINT chk_interview_reminders_status CHECK (status IN ('PENDING','DONE','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
