CREATE TABLE offers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    application_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    resume_version_id BIGINT UNSIGNED NOT NULL,
    company_name_snapshot VARCHAR(200) NOT NULL,
    role_snapshot VARCHAR(200) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'RECEIVED',
    base_salary DECIMAL(15,2) NOT NULL,
    salary_period VARCHAR(16) NOT NULL DEFAULT 'MONTHLY',
    salary_months DECIMAL(5,2) NOT NULL DEFAULT 12.00,
    currency CHAR(3) NOT NULL,
    guaranteed_bonus DECIMAL(15,2) NULL,
    variable_bonus_min DECIMAL(15,2) NULL,
    variable_bonus_max DECIMAL(15,2) NULL,
    equity_text VARCHAR(1000) NULL,
    housing_text VARCHAR(1000) NULL,
    work_time_text VARCHAR(1000) NULL,
    overtime_text VARCHAR(1000) NULL,
    location VARCHAR(240) NULL,
    remote_type VARCHAR(24) NULL,
    probation_months INT UNSIGNED NULL,
    probation_salary_ratio DECIMAL(5,4) NULL,
    start_date DATE NULL,
    deadline_at DATETIME(3) NULL,
    timezone VARCHAR(64) NOT NULL,
    notes VARCHAR(4000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_application_id BIGINT UNSIGNED GENERATED ALWAYS AS
        (CASE WHEN deleted_at IS NULL THEN application_id ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_offers_public_id (public_id),
    UNIQUE KEY uk_offers_active_application (active_application_id),
    KEY idx_offers_user_status_deadline (user_id, status, deadline_at, id),
    KEY idx_offers_user_company (user_id, company_id, updated_at DESC),
    CONSTRAINT fk_offers_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offers_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offers_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offers_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offers_resume FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE RESTRICT,
    CONSTRAINT chk_offers_status CHECK (status IN ('DRAFT','RECEIVED','CONSIDERING','ACCEPTED','DECLINED','EXPIRED','WITHDRAWN')),
    CONSTRAINT chk_offers_salary_period CHECK (salary_period IN ('MONTHLY','ANNUAL')),
    CONSTRAINT chk_offers_money CHECK (base_salary >= 0 AND salary_months > 0 AND salary_months <= 36
        AND (guaranteed_bonus IS NULL OR guaranteed_bonus >= 0)
        AND (variable_bonus_min IS NULL OR variable_bonus_min >= 0)
        AND (variable_bonus_max IS NULL OR variable_bonus_max >= 0)
        AND (variable_bonus_min IS NULL OR variable_bonus_max IS NULL OR variable_bonus_max >= variable_bonus_min)),
    CONSTRAINT chk_offers_probation CHECK (probation_months IS NULL OR probation_months <= 24),
    CONSTRAINT chk_offers_probation_ratio CHECK (probation_salary_ratio IS NULL OR probation_salary_ratio BETWEEN 0 AND 1),
    CONSTRAINT chk_offers_remote CHECK (remote_type IS NULL OR remote_type IN ('ONSITE','HYBRID','REMOTE','UNKNOWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE offer_benefits (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    offer_id BIGINT UNSIGNED NOT NULL,
    benefit_type VARCHAR(32) NOT NULL,
    name VARCHAR(160) NOT NULL,
    value_text VARCHAR(1000) NULL,
    quantified_value DECIMAL(15,2) NULL,
    currency CHAR(3) NULL,
    display_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_offer_benefits_public_id (public_id),
    KEY idx_offer_benefits_offer (offer_id, display_order, id),
    CONSTRAINT fk_offer_benefits_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_benefits_offer FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE RESTRICT,
    CONSTRAINT chk_offer_benefits_type CHECK (benefit_type IN ('CASH','INSURANCE','LEAVE','HOUSING','MEAL','TRANSPORT','LEARNING','HEALTH','EQUITY','OTHER')),
    CONSTRAINT chk_offer_benefits_value CHECK (quantified_value IS NULL OR quantified_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE offer_comparisons (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    comparison_version INT UNSIGNED NOT NULL,
    name VARCHAR(200) NOT NULL,
    offer_ids_json JSON NOT NULL,
    weights_json JSON NOT NULL,
    input_snapshot_json JSON NOT NULL,
    input_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    currency_group VARCHAR(40) NOT NULL,
    cash_comparable TINYINT(1) NOT NULL,
    summary_text VARCHAR(2000) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_offer_comparisons_public_id (public_id),
    UNIQUE KEY uk_offer_comparisons_version (user_id, comparison_version),
    UNIQUE KEY uk_offer_comparisons_idempotency (user_id, idempotency_key),
    KEY idx_offer_comparisons_user_time (user_id, created_at DESC, id DESC),
    CONSTRAINT fk_offer_comparisons_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE offer_comparison_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    comparison_id BIGINT UNSIGNED NOT NULL,
    offer_id BIGINT UNSIGNED NOT NULL,
    rank_no INT UNSIGNED NOT NULL,
    guaranteed_annual_cash DECIMAL(17,2) NOT NULL,
    potential_annual_cash DECIMAL(17,2) NULL,
    overall_score DECIMAL(7,2) NOT NULL,
    dimensions_json JSON NOT NULL,
    explanation_text VARCHAR(2000) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_offer_comparison_items_public_id (public_id),
    UNIQUE KEY uk_offer_comparison_item_offer (comparison_id, offer_id),
    KEY idx_offer_comparison_items_rank (comparison_id, rank_no, id),
    CONSTRAINT fk_offer_comparison_items_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_comparison_items_comparison FOREIGN KEY (comparison_id) REFERENCES offer_comparisons (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_comparison_items_offer FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE RESTRICT,
    CONSTRAINT chk_offer_comparison_items_score CHECK (overall_score BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE offer_deadlines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    offer_id BIGINT UNSIGNED NOT NULL,
    deadline_type VARCHAR(24) NOT NULL,
    title VARCHAR(240) NOT NULL,
    due_at DATETIME(3) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    completed_at DATETIME(3) NULL,
    cancelled_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    active_marker TINYINT GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL AND status='PENDING' THEN 1 ELSE NULL END) STORED,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_offer_deadlines_public_id (public_id),
    UNIQUE KEY uk_offer_deadlines_active (offer_id, deadline_type, due_at, active_marker),
    KEY idx_offer_deadlines_user_due (user_id, status, due_at, id),
    CONSTRAINT fk_offer_deadlines_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_offer_deadlines_offer FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE RESTRICT,
    CONSTRAINT chk_offer_deadlines_type CHECK (deadline_type IN ('DECISION','START','DOCUMENT','CUSTOM')),
    CONSTRAINT chk_offer_deadlines_status CHECK (status IN ('PENDING','DONE','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE analytics_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    schema_version VARCHAR(40) NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    input_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    result_json JSON NOT NULL,
    row_count INT UNSIGNED NOT NULL,
    generated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_analytics_snapshots_public_id (public_id),
    UNIQUE KEY uk_analytics_snapshots_idempotency (user_id, idempotency_key),
    KEY idx_analytics_snapshots_user_time (user_id, generated_at DESC, id DESC),
    CONSTRAINT fk_analytics_snapshots_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_analytics_snapshots_range CHECK (date_to >= date_from)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE privacy_operation_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    operation_type VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    scope_counts_json JSON NOT NULL,
    executed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    deleted_at DATETIME(3) NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_privacy_requests_public_id (public_id),
    UNIQUE KEY uk_privacy_requests_idempotency (user_id, idempotency_key),
    KEY idx_privacy_requests_user_time (user_id, created_at DESC, id DESC),
    CONSTRAINT fk_privacy_requests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_privacy_requests_type CHECK (operation_type IN ('EXPORT','DELETE_PREVIEW','DELETE_CONFIRM')),
    CONSTRAINT chk_privacy_requests_status CHECK (status IN ('PREVIEWED','COMPLETED','REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE analytics_daily
    DROP CHECK chk_analytics_daily_dimension,
    ADD CONSTRAINT chk_analytics_daily_dimension CHECK (dimension_type IN
        ('OVERALL','SOURCE','CITY','LEVEL','RECOMMENDATION_STATUS','PLATFORM','JOB_DIRECTION','COMPANY','SALARY_BAND','RESUME_VERSION','MATCH_SCORE_BUCKET'));
