<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from '../../utils/elementFeedback.js'
import { apiErrorMessage } from '../../api/http.js'
import { displayGeneratedText, displayText } from '../../utils/displayText.js'
import { listApplications } from '../../api/applications.js'
import { cancelOfferDeadline, completeOfferDeadline, createOffer, createOfferComparison, createOfferDeadline, getOffer, listOfferComparisons, listOfferDeadlines, listOffers, updateOffer, updateOfferStatus } from '../../api/offers.js'

const loading=ref(true), actionLoading=ref(false), createDialog=ref(false), compareDialog=ref(false), deadlineDialog=ref(false), editing=ref(false)
const offers=ref([]), deadlines=ref([]), comparisons=ref([]), applications=ref([]), selected=ref(null), selectedIds=ref([]), activeComparison=ref(null)
const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Shanghai'
const form=reactive({applicationId:'',baseSalary:20000,salaryPeriod:'MONTHLY',salaryMonths:13,currency:'CNY',guaranteedBonus:0,variableBonusMin:null,variableBonusMax:null,location:'',remoteType:'UNKNOWN',probationMonths:3,probationSalaryRatio:1,startDate:'',deadlineAt:'',timezone,notes:'',benefits:[]})
const compareForm=reactive({name:'Offer 对比',weights:{CASH:50,VARIABLE_BONUS:10,BENEFITS:10,GROWTH:10,WORK_LIFE:5,STABILITY:5,LOCATION:5,PREFERENCE:5}})
const deadlineForm=reactive({deadlineType:'CUSTOM',title:'Offer 跟进',dueAt:'',timezone})
const active= computed(()=>offers.value.filter(o=>!['ACCEPTED','DECLINED','EXPIRED','WITHDRAWN'].includes(o.status)).length)

onMounted(load)
async function load(preferred){loading.value=true;try{const [o,d,c,a]=await Promise.all([listOffers({page:1,size:100}),listOfferDeadlines(),listOfferComparisons(),listApplications({status:'OFFER'})]);offers.value=o.data.data.items;deadlines.value=d.data.data;comparisons.value=c.data.data;applications.value=a.data.data.items||[];const id=preferred||selected.value?.id||offers.value[0]?.id;if(id)selected.value=(await getOffer(id)).data.data;else selected.value=null}catch(e){ElMessage.error(apiErrorMessage(e,'Offer 中心加载失败'))}finally{loading.value=false}}
function openCreate(){editing.value=false;Object.assign(form,{applicationId:'',baseSalary:20000,salaryPeriod:'MONTHLY',salaryMonths:13,currency:'CNY',guaranteedBonus:0,variableBonusMin:null,variableBonusMax:null,location:'',remoteType:'UNKNOWN',probationMonths:3,probationSalaryRatio:1,startDate:'',deadlineAt:'',timezone,notes:'',benefits:[]});createDialog.value=true}
function openEdit(){editing.value=true;Object.assign(form,{applicationId:selected.value.applicationId,baseSalary:selected.value.baseSalary,salaryPeriod:selected.value.salaryPeriod,salaryMonths:selected.value.salaryMonths,currency:selected.value.currency,guaranteedBonus:selected.value.guaranteedBonus,variableBonusMin:selected.value.variableBonusMin,variableBonusMax:selected.value.variableBonusMax,location:selected.value.location||'',remoteType:selected.value.remoteType||'UNKNOWN',probationMonths:selected.value.probationMonths,probationSalaryRatio:selected.value.probationSalaryRatio,startDate:selected.value.startDate||'',deadlineAt:selected.value.deadlineAt?localInput(selected.value.deadlineAt):'',timezone:selected.value.timezone,notes:selected.value.notes||'',benefits:selected.value.benefits.map(v=>({benefitType:v.benefitType,name:v.name,value:v.value,quantifiedValue:v.quantifiedValue,currency:v.currency,displayOrder:v.displayOrder}))});createDialog.value=true}
async function submit(){if(!form.applicationId)return ElMessage.warning('请选择已进入 OFFER 阶段的投递');actionLoading.value=true;try{const payload={...form,startDate:form.startDate||null,deadlineAt:form.deadlineAt?localWithOffset(form.deadlineAt):null,guaranteedBonus:Number(form.guaranteedBonus)||null,variableBonusMin:form.variableBonusMin===''?null:form.variableBonusMin,variableBonusMax:form.variableBonusMax===''?null:form.variableBonusMax,location:form.location||null,notes:form.notes||null};let response;if(editing.value){delete payload.applicationId;payload.version=selected.value.version;response=await updateOffer(selected.value.id,payload)}else response=await createOffer(payload);createDialog.value=false;ElMessage.success(editing.value?'Offer 修改已保存':'Offer 已保存到真实数据库');await load(response.data.data.id)}catch(e){ElMessage.error(apiErrorMessage(e,editing.value?'修改 Offer 失败':'创建 Offer 失败'))}finally{actionLoading.value=false}}
function addBenefit(){form.benefits.push({benefitType:'OTHER',name:'',value:'',quantifiedValue:null,currency:form.currency,displayOrder:form.benefits.length})}
async function submitDeadline(){if(!deadlineForm.title||!deadlineForm.dueAt)return ElMessage.warning('请填写截止事项');try{await createOfferDeadline({offerId:selected.value.id,deadlineType:deadlineForm.deadlineType,title:deadlineForm.title,dueAt:localWithOffset(deadlineForm.dueAt),timezone:deadlineForm.timezone});deadlineDialog.value=false;ElMessage.success('截止事项已保存');await load(selected.value.id)}catch(e){ElMessage.error(apiErrorMessage(e,'创建截止事项失败'))}}
async function transition(status){if(!selected.value)return;actionLoading.value=true;try{await updateOfferStatus(selected.value.id,status,selected.value.version);ElMessage.success(`Offer 状态已更新为“${displayText(status)}”`);await load(selected.value.id)}catch(e){ElMessage.error(apiErrorMessage(e,'状态更新失败'))}finally{actionLoading.value=false}}
async function deadlineAction(item,done){try{await(done?completeOfferDeadline(item.id,item.version):cancelOfferDeadline(item.id,item.version));ElMessage.success(done?'截止事项已完成':'截止事项已取消');await load(selected.value?.id)}catch(e){ElMessage.error(apiErrorMessage(e,'截止事项更新失败'))}}
async function compare(){if(selectedIds.value.length<2)return ElMessage.warning('至少选择两个 Offer');actionLoading.value=true;try{const response=await createOfferComparison({name:compareForm.name,offerIds:selectedIds.value,weights:compareForm.weights,ratings:{}});activeComparison.value=response.data.data;compareDialog.value=false;ElMessage.success('不可变对比快照已创建');await load(selected.value?.id)}catch(e){ElMessage.error(apiErrorMessage(e,'Offer 对比失败'))}finally{actionLoading.value=false}}
async function openComparison(item){activeComparison.value=item}
function toggle(id,checked){selectedIds.value=checked?[...new Set([...selectedIds.value,id])]:selectedIds.value.filter(v=>v!==id)}
function money(v,c){return v==null?'未知':`${Number(v).toLocaleString('zh-CN')} ${c||''}`}
function time(v){return v?new Date(v).toLocaleString('zh-CN'):'—'}
function localWithOffset(value){const date=new Date(value),total=-date.getTimezoneOffset(),sign=total>=0?'+':'-',pad=n=>String(n).padStart(2,'0');return `${value.length===16?value+':00':value}${sign}${pad(Math.floor(Math.abs(total)/60))}:${pad(Math.abs(total)%60)}`}
function localInput(value){const d=new Date(value),pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
</script>

<template>
<section v-loading="loading" class="page-section offer-center">
  <div class="page-heading"><div><p class="eyebrow accent">阶段 9 · 决策支持</p><h1>Offer 中心</h1><p>记录真实 Offer、截止事项与可追溯对比。跨币种时不会虚构汇率。</p></div><div class="heading-actions"><el-button :disabled="selectedIds.length<2" @click="compareDialog=true">对比 {{ selectedIds.length||'' }}</el-button><el-button type="primary" @click="openCreate">新增 Offer</el-button></div></div>
  <div class="interview-boundary"><strong>决策边界</strong><span>主观评分只来自你的输入；未知项不当作 0 分，系统不自动接受或拒绝 Offer。</span></div>
  <div class="interview-metrics"><div><span>全部 Offer</span><strong>{{offers.length}}</strong></div><div><span>进行中</span><strong>{{active}}</strong></div><div><span>待办截止</span><strong>{{deadlines.filter(d=>d.status==='PENDING').length}}</strong></div><div><span>对比快照</span><strong>{{comparisons.length}}</strong></div></div>
  <div class="offer-workspace">
    <aside class="surface offer-list"><header><span class="section-kicker">OFFER 列表</span><h2>机会列表</h2></header><button v-for="item in offers" :key="item.id" :class="{active:selected?.id===item.id}" @click="selected=item"><el-checkbox :model-value="selectedIds.includes(item.id)" @click.stop @change="v=>toggle(item.id,v)"/><div><strong>{{item.companyName}}</strong><span>{{item.role}}</span><small>{{money(item.guaranteedAnnualCash,item.currency)}}</small></div><em>{{displayText(item.status)}}</em></button><div v-if="!offers.length" class="empty-state">申请进入 Offer 阶段后，可在这里创建真实 Offer。</div></aside>
    <main v-if="selected" class="surface offer-detail"><header><div><span class="section-kicker">{{displayText(selected.status)}} · {{selected.currency}}</span><h2>{{selected.companyName}}</h2><p>{{selected.role}} · 更新 {{time(selected.updatedAt)}}</p></div><div class="heading-actions"><el-button @click="openEdit">编辑</el-button><el-dropdown @command="transition"><el-button>更新状态</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item v-for="s in ['CONSIDERING','ACCEPTED','DECLINED','EXPIRED','WITHDRAWN']" :key="s" :command="s">{{displayText(s)}}</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></header>
      <div class="offer-money"><div><span>保证年现金</span><strong>{{money(selected.guaranteedAnnualCash,selected.currency)}}</strong></div><div><span>潜在年现金</span><strong>{{money(selected.potentialAnnualCash,selected.currency)}}</strong></div><div><span>试用月现金</span><strong>{{money(selected.probationMonthlyCash,selected.currency)}}</strong></div></div>
      <section><h3>薪酬事实</h3><div class="offer-facts"><p>基础薪资 <b>{{money(selected.baseSalary,selected.currency)}} / {{displayText(selected.salaryPeriod)}}</b></p><p>计薪月数 <b>{{selected.salaryMonths}}</b></p><p>保证奖金 <b>{{money(selected.guaranteedBonus,selected.currency)}}</b></p><p>浮动奖金 <b>{{money(selected.variableBonusMin,selected.currency)}} – {{money(selected.variableBonusMax,selected.currency)}}</b></p><p>地点 <b>{{selected.location||'未填写'}} · {{displayText(selected.remoteType||'UNKNOWN')}}</b></p><p>决策截止 <b>{{time(selected.deadlineAt)}}</b></p></div></section>
      <section><h3>福利明细</h3><article v-for="benefit in selected.benefits" :key="benefit.id" class="benefit-row"><span>{{displayText(benefit.benefitType)}}</span><strong>{{benefit.name}}</strong><small>{{benefit.value||money(benefit.quantifiedValue,benefit.currency)}}</small></article><p v-if="!selected.benefits.length" class="muted">暂无结构化福利。</p></section><section><h3>备注</h3><p class="muted">{{selected.notes||'暂无备注'}}</p></section>
    </main><div v-else class="surface empty-state centered">选择一个 Offer 查看决策事实。</div>
    <aside class="surface offer-deadlines"><header><span class="section-kicker">截止事项</span><h2>截止与历史</h2><el-button text :disabled="!selected" @click="deadlineDialog=true">新增</el-button></header><article v-for="item in deadlines" :key="item.id"><div><strong>{{item.title}}</strong><span>{{item.companyName}} · {{time(item.dueAt)}}</span></div><em>{{displayText(item.status)}}</em><div v-if="item.status==='PENDING'"><el-button text @click="deadlineAction(item,true)">完成</el-button><el-button text @click="deadlineAction(item,false)">取消</el-button></div></article><h3>对比快照</h3><button v-for="item in comparisons" :key="item.id" class="comparison-link" @click="openComparison(item)">{{item.name}} <span>v{{item.comparisonVersion}}</span></button></aside>
  </div>
  <section v-if="activeComparison" class="surface comparison-result"><div class="section-heading"><div><span class="section-kicker">不可变快照 · V{{activeComparison.comparisonVersion}}</span><h2>{{activeComparison.name}}</h2></div><span>{{displayGeneratedText(activeComparison.summary)}}</span></div><div class="comparison-table"><article v-for="item in activeComparison.items" :key="item.id"><b>#{{item.rank}}</b><div><strong>{{item.companyName}} · {{item.role}}</strong><span>{{displayGeneratedText(item.explanation)}}</span><div class="dimension-chips"><small v-for="dimension in item.dimensions" :key="dimension.key">{{displayText(dimension.key)}} {{dimension.unknown?'未知':dimension.normalizedScore}}</small></div></div><em>{{Number(item.overallScore).toFixed(2)}}</em></article></div></section>
  <el-dialog v-model="createDialog" :title="editing?'编辑 Offer':'创建真实 Offer'" width="720"><el-form label-position="top"><div class="dialog-grid"><el-form-item label="Offer 阶段投递"><el-select v-model="form.applicationId" :disabled="editing"><el-option v-for="a in applications" :key="a.id" :value="a.id" :label="`${a.job.companyName} · ${a.job.title}`"/></el-select></el-form-item><el-form-item label="币种"><el-input v-model="form.currency" maxlength="3"/></el-form-item><el-form-item label="基础薪资"><el-input-number v-model="form.baseSalary" :min="0"/></el-form-item><el-form-item label="薪资周期"><el-select v-model="form.salaryPeriod"><el-option value="MONTHLY" label="月薪"/><el-option value="ANNUAL" label="年薪"/></el-select></el-form-item><el-form-item label="计薪月数"><el-input-number v-model="form.salaryMonths" :min="1" :max="36"/></el-form-item><el-form-item label="保证奖金"><el-input-number v-model="form.guaranteedBonus" :min="0"/></el-form-item><el-form-item label="决策截止"><el-input v-model="form.deadlineAt" type="datetime-local"/></el-form-item><el-form-item label="地点"><el-input v-model="form.location"/></el-form-item><el-form-item label="备注" class="wide"><el-input v-model="form.notes" type="textarea"/></el-form-item></div><div class="benefit-editor"><header><strong>结构化福利</strong><el-button text @click="addBenefit">新增福利</el-button></header><div v-for="(benefit,index) in form.benefits" :key="index"><el-select v-model="benefit.benefitType"><el-option v-for="type in ['INSURANCE','LEAVE','HOUSING','MEAL','TRANSPORT','LEARNING','HEALTH','EQUITY','OTHER']" :key="type" :value="type" :label="displayText(type)"/></el-select><el-input v-model="benefit.name" placeholder="福利名称"/><el-input-number v-model="benefit.quantifiedValue" :min="0" placeholder="明确金额"/><el-button text type="danger" @click="form.benefits.splice(index,1)">移除</el-button></div></div></el-form><template #footer><el-button @click="createDialog=false">取消</el-button><el-button type="primary" :loading="actionLoading" @click="submit">保存 Offer</el-button></template></el-dialog>
  <el-dialog v-model="deadlineDialog" title="新增站内截止事项" width="520"><el-form label-position="top"><el-form-item label="类型"><el-select v-model="deadlineForm.deadlineType"><el-option value="DECISION" label="决策"/><el-option value="START" label="入职"/><el-option value="DOCUMENT" label="材料"/><el-option value="CUSTOM" label="自定义"/></el-select></el-form-item><el-form-item label="标题"><el-input v-model="deadlineForm.title"/></el-form-item><el-form-item label="时间"><el-input v-model="deadlineForm.dueAt" type="datetime-local"/></el-form-item></el-form><template #footer><el-button @click="deadlineDialog=false">取消</el-button><el-button type="primary" @click="submitDeadline">保存</el-button></template></el-dialog>
  <el-dialog v-model="compareDialog" title="创建不可变 Offer 对比" width="650"><el-alert title="现金维度只在币种一致时比较；其余主观维度缺失时显示“未知”。" type="info" :closable="false"/><el-form label-position="top"><el-form-item label="快照名称"><el-input v-model="compareForm.name"/></el-form-item><div class="weight-grid"><label v-for="(value,key) in compareForm.weights" :key="key"><span>{{displayText(key)}}</span><el-input-number v-model="compareForm.weights[key]" :min="0" :max="100"/></label></div></el-form><template #footer><span>权重合计 {{Object.values(compareForm.weights).reduce((a,b)=>a+Number(b),0)}}</span><el-button type="primary" :loading="actionLoading" @click="compare">创建快照</el-button></template></el-dialog>
</section>
</template>
