param([switch]$VerifyPersistence)

$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$baseUrl='http://127.0.0.1:8088'
$statePath=Join-Path $projectRoot 'scripts\.phase9-smoke-state.json'

function Read-Env([string]$Name){$line=Get-Content -LiteralPath (Join-Path $projectRoot '.env')|Where-Object{$_ -match ('^\s*'+[regex]::Escape($Name)+'\s*=')}|Select-Object -Last 1;if(-not $line){throw "Missing local environment value: $Name"};$value=($line -split '=',2)[1].Trim();if(($value.StartsWith('"')-and$value.EndsWith('"'))-or($value.StartsWith("'")-and$value.EndsWith("'"))){$value=$value.Substring(1,$value.Length-2)};return $value}
function New-Password([string]$Scope){$sha=[Security.Cryptography.SHA256]::Create();try{$hex=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes("$Scope|$(Read-Env 'JWT_SECRET')")))).Replace('-','');return "P9!$($hex.Substring(0,30))z"}finally{$sha.Dispose()}}
function New-Bcrypt([string]$Password){$crypto=Get-ChildItem "$env:USERPROFILE\.m2\repository\org\springframework\security\spring-security-crypto" -Recurse -Filter 'spring-security-crypto-*.jar'|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$jcl=Get-ChildItem "$env:USERPROFILE\.m2\repository\org\springframework\spring-jcl" -Recurse -Filter 'spring-jcl-*.jar'|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$env:JOBPILOT_RESET_PASSWORD=$Password;try{$value=((& java --class-path ($crypto.FullName+';'+$jcl.FullName) (Join-Path $PSScriptRoot 'GenerateBcrypt.java'))-join '').Trim()}finally{Remove-Item Env:JOBPILOT_RESET_PASSWORD -ErrorAction SilentlyContinue};if($value-notmatch '^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$'){throw 'BCrypt generation failed'};return $value}
function Public-Id([string]$Prefix){return ($Prefix+[Guid]::NewGuid().ToString('N')).Substring(0,26).ToUpperInvariant()}
function Api([string]$Method,[string]$Path,[hashtable]$Headers,$Body=$null){$p=@{Method=$Method;Uri="$baseUrl$Path";Headers=$Headers;TimeoutSec=40};if($null-ne$Body){$p.ContentType='application/json';$p.Body=$Body|ConvertTo-Json -Depth 30 -Compress};return Invoke-RestMethod @p}
function Expect([int]$Status,[scriptblock]$Action,[string]$Label){try{$null=&$Action;throw "$Label unexpectedly succeeded"}catch{$actual=[int]$_.Exception.Response.StatusCode;if($actual-ne$Status){throw "$Label expected HTTP $Status but received $actual"}}}
function Assert([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Login([string]$Name,[string]$Password){return Api 'POST' '/api/v1/auth/login' @{} @{login=$Name;password=$Password}}
function Seed([string]$Password,[string]$IntruderPassword){
  $hash=New-Bcrypt $Password;$intruderHash=New-Bcrypt $IntruderPassword;$suffix=[Guid]::NewGuid().ToString('N').Substring(0,10)
  $userPublic=Public-Id 'P9U';$intruderPublic=Public-Id 'P9I';$resumePublic=Public-Id 'P9R';$versionPublic=Public-Id 'P9V'
  $company1=Public-Id 'P9C';$company2=Public-Id 'P9D';$company3=Public-Id 'P9E';$company4=Public-Id 'P9F'
  $jobs=1..4|ForEach-Object{Public-Id "P9J$_"};$sources=1..4|ForEach-Object{Public-Id "P9S$_"};$apps=1..4|ForEach-Object{Public-Id "P9A$_"}
  $sql=@"
INSERT INTO users(public_id,username,email,password_hash,display_name,status,created_at,updated_at) VALUES('$userPublic','phase9_smoke','phase9-smoke@local.invalid','$hash','Phase 9 Smoke','ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),status='ACTIVE',deleted_at=NULL,updated_at=UTC_TIMESTAMP(3);
INSERT INTO users(public_id,username,email,password_hash,display_name,status,created_at,updated_at) VALUES('$intruderPublic','phase9_privacy','phase9-privacy@local.invalid','$intruderHash','Phase 9 Privacy','ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),status='ACTIVE',deleted_at=NULL,updated_at=UTC_TIMESTAMP(3);
SET @uid=(SELECT id FROM users WHERE username='phase9_smoke'); SET @iid=(SELECT id FROM users WHERE username='phase9_privacy');
UPDATE refresh_tokens SET revoked_at=COALESCE(revoked_at,UTC_TIMESTAMP(3)),updated_at=UTC_TIMESTAMP(3) WHERE user_id IN (@uid,@iid) AND deleted_at IS NULL;
INSERT INTO candidate_profiles(public_id,user_id,target_cities_json,target_roles_json,target_industries_json,target_company_types_json,salary_currency,accept_remote,accept_relocation,profile_completeness,created_at,updated_at) SELECT '$(Public-Id 'P9P')',@iid,'[]','[]','[]','[]','CNY',0,0,0,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE NOT EXISTS(SELECT 1 FROM candidate_profiles WHERE user_id=@iid AND deleted_at IS NULL);
SET @rid=(SELECT id FROM resumes WHERE user_id=@uid AND deleted_at IS NULL LIMIT 1);
INSERT INTO resumes(public_id,user_id,name,target_role,master,default_resume,status,created_at,updated_at) SELECT '$resumePublic',@uid,'Phase 9 Master','Java Backend',1,1,'ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE @rid IS NULL;
SET @rid=COALESCE(@rid,LAST_INSERT_ID()); SET @rvid=(SELECT current_version_id FROM resumes WHERE id=@rid);
INSERT INTO resume_versions(public_id,resume_id,version_number,version_name,content_json,rendered_text,source_type,created_by,active,content_hash,created_at,updated_at) SELECT '$versionPublic',@rid,1,'Phase 9 v1','{}','Java Spring Boot MySQL Redis','MANUAL','USER',1,REPEAT('a',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE @rvid IS NULL;
SET @rvid=COALESCE(@rvid,LAST_INSERT_ID()); UPDATE resumes SET current_version_id=@rvid WHERE id=@rid AND current_version_id IS NULL;
INSERT INTO companies(public_id,normalized_name,display_name,risk_flags_json,created_at,updated_at) VALUES('$company1','phase9-alpha-$suffix','Phase 9 Alpha $suffix','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$company2','phase9-beta-$suffix','Phase 9 Beta $suffix','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$company3','phase9-global-$suffix','Phase 9 Global $suffix','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$company4','phase9-delete-$suffix','Phase 9 Delete $suffix','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3));
SET @c1=(SELECT id FROM companies WHERE public_id='$company1');SET @c2=(SELECT id FROM companies WHERE public_id='$company2');SET @c3=(SELECT id FROM companies WHERE public_id='$company3');SET @c4=(SELECT id FROM companies WHERE public_id='$company4');
INSERT INTO jobs(public_id,user_id,company_id,title,normalized_title,canonical_job_key,fingerprint_hash,city,remote_type,salary_min,salary_max,salary_months,currency,job_type,description_raw,description_clean,responsibilities_json,requirements_json,first_collected_at,last_collected_at,status,parse_status,raw_content_hash,parse_result_json,manual_fields_json,created_at,updated_at) VALUES
('$($jobs[0])',@uid,@c1,'Senior Java Engineer','java backend',SHA2(CONCAT('k1','$suffix'),256),SHA2(CONCAT('f1','$suffix'),256),'Shanghai','HYBRID',30000,45000,13,'CNY','FULL_TIME','Spring Boot MySQL Redis','Spring Boot MySQL Redis','[]','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'ACTIVE','SUCCESS',SHA2(CONCAT('r1','$suffix'),256),'{}','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),
('$($jobs[1])',@uid,@c2,'Platform Engineer','platform backend',SHA2(CONCAT('k2','$suffix'),256),SHA2(CONCAT('f2','$suffix'),256),'Hangzhou','REMOTE',28000,42000,14,'CNY','FULL_TIME','Java Kafka Cloud','Java Kafka Cloud','[]','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'ACTIVE','SUCCESS',SHA2(CONCAT('r2','$suffix'),256),'{}','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),
('$($jobs[2])',@uid,@c3,'Global Backend Engineer','global backend',SHA2(CONCAT('k3','$suffix'),256),SHA2(CONCAT('f3','$suffix'),256),'Singapore','ONSITE',6000,9000,12,'USD','FULL_TIME','Java distributed systems','Java distributed systems','[]','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'ACTIVE','SUCCESS',SHA2(CONCAT('r3','$suffix'),256),'{}','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),
('$($jobs[3])',@uid,@c4,'Temporary Engineer','temporary backend',SHA2(CONCAT('k4','$suffix'),256),SHA2(CONCAT('f4','$suffix'),256),'Shanghai','ONSITE',10000,15000,12,'CNY','FULL_TIME','Temporary','Temporary','[]','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'ACTIVE','SUCCESS',SHA2(CONCAT('r4','$suffix'),256),'{}','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3));
SET @j1=(SELECT id FROM jobs WHERE public_id='$($jobs[0])');SET @j2=(SELECT id FROM jobs WHERE public_id='$($jobs[1])');SET @j3=(SELECT id FROM jobs WHERE public_id='$($jobs[2])');SET @j4=(SELECT id FROM jobs WHERE public_id='$($jobs[3])');
INSERT INTO job_sources(public_id,user_id,job_id,platform,platform_job_id,source_type,raw_snapshot_json,collected_at,last_seen_at,availability_status,user_initiated,created_at,updated_at) VALUES
('$($sources[0])',@uid,@j1,'MANUAL','p9-1-$suffix','MANUAL','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'AVAILABLE',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($sources[1])',@uid,@j2,'EXTENSION','p9-2-$suffix','EXTENSION','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'AVAILABLE',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($sources[2])',@uid,@j3,'MANUAL','p9-3-$suffix','MANUAL','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'AVAILABLE',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($sources[3])',@uid,@j4,'MANUAL','p9-4-$suffix','MANUAL','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'AVAILABLE',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3));
SET @s1=(SELECT id FROM job_sources WHERE public_id='$($sources[0])');SET @s2=(SELECT id FROM job_sources WHERE public_id='$($sources[1])');SET @s3=(SELECT id FROM job_sources WHERE public_id='$($sources[2])');SET @s4=(SELECT id FROM job_sources WHERE public_id='$($sources[3])');
INSERT INTO applications(public_id,user_id,job_id,job_source_id,resume_version_id,status,application_mode,applied_at,last_status_at,idempotency_key,request_hash,created_at,updated_at) VALUES
('$($apps[0])',@uid,@j1,@s1,@rvid,'OFFER','MANUAL',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'p9-a1-$suffix',REPEAT('1',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($apps[1])',@uid,@j2,@s2,@rvid,'OFFER','ASSIST',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'p9-a2-$suffix',REPEAT('2',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($apps[2])',@uid,@j3,@s3,@rvid,'OFFER','MANUAL',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'p9-a3-$suffix',REPEAT('3',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)),('$($apps[3])',@uid,@j4,@s4,@rvid,'OFFER','MANUAL',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),'p9-a4-$suffix',REPEAT('4',64),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3));
SET @a1=(SELECT id FROM applications WHERE public_id='$($apps[0])');SET @a2=(SELECT id FROM applications WHERE public_id='$($apps[1])');SET @a3=(SELECT id FROM applications WHERE public_id='$($apps[2])');SET @a4=(SELECT id FROM applications WHERE public_id='$($apps[3])');
INSERT INTO application_logs(public_id,application_id,user_id,from_status,to_status,event_type,occurred_at,source,actor_user_id,note,evidence_json,trace_id,created_at) VALUES('$(Public-Id 'P9L')',@a1,@uid,'APPLIED','REPLIED','STATUS_TRANSITION',UTC_TIMESTAMP(3),'USER',@uid,'Phase 9 fact','{}','phase9-smoke',UTC_TIMESTAMP(3)),('$(Public-Id 'P9L')',@a1,@uid,'REPLIED','OFFER','STATUS_TRANSITION',UTC_TIMESTAMP(3),'USER',@uid,'Phase 9 fact','{}','phase9-smoke',UTC_TIMESTAMP(3));
"@
  $sql|docker compose exec -T mysql sh -lc 'MYSQL_PWD="$MYSQL_PASSWORD" mysql -u"$MYSQL_USER" "$MYSQL_DATABASE"';if($LASTEXITCODE-ne0){throw 'Phase 9 seed failed'}
  return @{apps=$apps;suffix=$suffix}
}

Push-Location $projectRoot
try{
 Assert((Invoke-RestMethod "$baseUrl/actuator/health" -TimeoutSec 8).status-eq'UP')'Backend is unavailable';Assert((docker compose exec -T redis redis-cli ping)-match'PONG')'Redis is unavailable'
 $password=New-Password 'phase9-smoke';$intruderPassword=New-Password 'phase9-privacy'
 if($VerifyPersistence){$state=Get-Content $statePath -Raw|ConvertFrom-Json;$login=Login 'phase9_smoke' $password;$headers=@{Authorization="Bearer $($login.data.accessToken)"};$offers=(Api 'GET' '/api/v1/offers?page=1&size=100' $headers).data;Assert(@($offers.items|Where-Object{$_.id-eq$state.offerId}).Count-eq1)'Persisted Offer missing';$comparison=Api 'GET' "/api/v1/offers/comparisons/$($state.comparisonId)" $headers;Assert($comparison.data.items.Count-eq2)'Persisted comparison missing';$snapshot=Api 'GET' "/api/v1/analytics/snapshots/$($state.snapshotId)" $headers;Assert($snapshot.data.schemaVersion-eq'PHASE9_V1')'Persisted Analytics snapshot missing';[pscustomobject]@{status='PASS';mode='PERSISTENCE';httpCount=3;offerId=$state.offerId}|ConvertTo-Json -Compress;exit 0}
 $seed=Seed $password $intruderPassword;$login=Login 'phase9_smoke' $password;$intruder=Login 'phase9_privacy' $intruderPassword;$headers=@{Authorization="Bearer $($login.data.accessToken)";'X-Trace-Id'="phase9-$([Guid]::NewGuid().ToString('N'))"};$intruderHeaders=@{Authorization="Bearer $($intruder.data.accessToken)"}
 $future=[DateTimeOffset]::Now.ToOffset([TimeSpan]::FromHours(8)).AddDays(7).ToString('yyyy-MM-ddTHH:mm:sszzz')
 function New-Offer($app,$base,$currency,$benefit){return Api 'POST' '/api/v1/offers' $headers @{applicationId=$app;baseSalary=$base;salaryPeriod='MONTHLY';salaryMonths=13;currency=$currency;guaranteedBonus=10000;variableBonusMin=5000;variableBonusMax=20000;location='Shanghai';remoteType='HYBRID';probationMonths=3;probationSalaryRatio=0.9;deadlineAt=$future;timezone='Asia/Shanghai';notes='Phase 9 HTTP fact';benefits=@(@{benefitType='LEARNING';name='Learning budget';value='Explicit annual budget';quantifiedValue=$benefit;currency=$currency;displayOrder=1})}}
 $o1=New-Offer $seed.apps[0] 30000 'CNY' 10000;$o2=New-Offer $seed.apps[1] 28000 'CNY' 20000;$o3=New-Offer $seed.apps[2] 8000 'USD' 2000;$temp=New-Offer $seed.apps[3] 10000 'CNY' 1000
 Assert($o1.data.guaranteedAnnualCash-eq400000)'Offer calculation failed';Assert($o1.data.benefits.Count-eq1)'Benefits failed';Expect 409 {New-Offer $seed.apps[0] 1 'CNY' 1}'Duplicate Offer'
 $updated=Api 'PUT' "/api/v1/offers/$($o1.data.id)" $headers @{baseSalary=31000;salaryPeriod='MONTHLY';salaryMonths=13;currency='CNY';guaranteedBonus=10000;variableBonusMin=5000;variableBonusMax=21000;location='Shanghai';remoteType='HYBRID';probationMonths=3;probationSalaryRatio=0.9;deadlineAt=$future;timezone='Asia/Shanghai';notes='Updated through HTTP';benefits=@();version=$o1.data.version}
 Expect 409 {Api 'PUT' "/api/v1/offers/$($o1.data.id)" $headers @{baseSalary=1;salaryPeriod='MONTHLY';salaryMonths=12;currency='CNY';timezone='Asia/Shanghai';version=$o1.data.version}}'Offer optimistic lock'
 $considering=Api 'POST' "/api/v1/offers/$($o1.data.id):status" $headers @{status='CONSIDERING';version=$updated.data.version};Assert($considering.data.status-eq'CONSIDERING')'Offer transition failed'
 Expect 404 {Api 'GET' "/api/v1/offers/$($o1.data.id)" $intruderHeaders}'Offer ownership'
 $deadline=Api 'POST' '/api/v1/offer-deadlines' $headers @{offerId=$o1.data.id;deadlineType='DOCUMENT';title='Return documents';dueAt=$future;timezone='Asia/Shanghai'};$done=Api 'POST' "/api/v1/offer-deadlines/$($deadline.data.id):done" $headers @{version=$deadline.data.version};Assert($done.data.status-eq'DONE')'Deadline lifecycle failed'
 $weights=@{CASH=50;VARIABLE_BONUS=10;BENEFITS=10;GROWTH=10;WORK_LIFE=5;STABILITY=5;LOCATION=5;PREFERENCE=5};$key="p9-cmp-$($seed.suffix)";$cmpHeaders=$headers.Clone();$cmpHeaders['Idempotency-Key']=$key
 $comparison=Api 'POST' '/api/v1/offers/comparisons' $cmpHeaders @{name='CNY comparison';offerIds=@($o1.data.id,$o2.data.id);weights=$weights;ratings=@{}};$replay=Api 'POST' '/api/v1/offers/comparisons' $cmpHeaders @{name='CNY comparison';offerIds=@($o1.data.id,$o2.data.id);weights=$weights;ratings=@{}};Assert($comparison.data.id-eq$replay.data.id-and$comparison.data.cashComparable)'Comparison idempotency failed';Expect 409 {Api 'POST' '/api/v1/offers/comparisons' $cmpHeaders @{name='changed';offerIds=@($o1.data.id,$o2.data.id);weights=$weights;ratings=@{}}}'Comparison idempotency conflict'
 $crossHeaders=$headers.Clone();$crossHeaders['Idempotency-Key']="p9-cross-$($seed.suffix)";$cross=Api 'POST' '/api/v1/offers/comparisons' $crossHeaders @{name='Cross currency';offerIds=@($o1.data.id,$o3.data.id);weights=$weights;ratings=@{}};Assert(-not$cross.data.cashComparable-and$cross.data.currencyGroup-eq'MULTI_CURRENCY')'Cross-currency safety failed'
 $list=Api 'GET' '/api/v1/offers?page=1&size=100&currency=CNY' $headers;Assert($list.data.total-ge3)'Offer list/filter failed';$dashboard=Api 'GET' '/api/v1/offers/dashboard' $headers;Assert($dashboard.data.activeOffers-ge3)'Offer dashboard failed'
 Api 'DELETE' "/api/v1/offers/$($temp.data.id)" $headers|Out-Null;Expect 404 {Api 'GET' "/api/v1/offers/$($temp.data.id)" $headers}'Offer logical delete'
 $today=(Get-Date).ToString('yyyy-MM-dd');$from=(Get-Date).AddDays(-2).ToString('yyyy-MM-dd');$analytics=Api 'GET' "/api/v1/analytics/complete?from=$from&to=$today" $headers;Assert($analytics.data.funnel[0].denominator-ge4)'Complete Analytics funnel failed';Assert($null-ne$analytics.data.dimensions.PLATFORM)'Analytics dimensions missing';$platformStages=@($analytics.data.dimensions.PLATFORM|ForEach-Object{($_.key-split'::')[-1]}|Sort-Object -Unique);Assert((@($platformStages|Where-Object{$_-in@('REPLIED','INTERVIEW','OFFER')}).Count)-eq3)'Analytics dimension stages missing';$zero=Api 'GET' '/api/v1/analytics/complete?from=2020-01-01&to=2020-01-02' $headers;Assert($null-eq$zero.data.funnel[0].rate)'Zero-denominator rate must be null'
 $snapHeaders=$headers.Clone();$snapHeaders['Idempotency-Key']="p9-snapshot-$($seed.suffix)";$snapshot=Api 'POST' '/api/v1/analytics:rebuild' $snapHeaders @{from=$from;to=$today};$snapReplay=Api 'POST' '/api/v1/analytics:rebuild' $snapHeaders @{from=$from;to=$today};Assert($snapshot.data.id-eq$snapReplay.data.id)'Analytics rebuild idempotency failed';Assert($snapshot.data.inputHash-eq$snapReplay.data.inputHash)'Analytics rebuild hash reconciliation failed';$first=@($snapshot.data.result.funnel);$second=@($snapReplay.data.result.funnel);Assert($first.Count-eq$second.Count)'Analytics rebuild stage reconciliation failed';for($i=0;$i-lt$first.Count;$i++){Assert(($first[$i].key-eq$second[$i].key)-and($first[$i].numerator-eq$second[$i].numerator)-and($first[$i].denominator-eq$second[$i].denominator)-and($first[$i].sampleSize-eq$second[$i].sampleSize)-and([decimal]$first[$i].rate-eq[decimal]$second[$i].rate)-and($first[$i].insufficientSample-eq$second[$i].insufficientSample))"Analytics rebuild metric reconciliation failed at $($first[$i].key)"}
 $export=Api 'GET' '/api/v1/privacy/export' $headers;Assert($export.data.data.offers.Count-ge3)'Privacy export missing Offer data';$previewHeaders=$headers.Clone();$previewHeaders['Idempotency-Key']="p9-preview-$($seed.suffix)";$preview=Api 'POST' '/api/v1/privacy/deletions:preview' $previewHeaders;Assert($preview.data.confirmationPhrase-eq'DELETE MY JOBPILOT DATA')'Privacy preview failed'
 $privacyPreviewHeaders=$intruderHeaders.Clone();$privacyPreviewHeaders['Idempotency-Key']="p9-delete-preview-$($seed.suffix)";$privacyPreview=Api 'POST' '/api/v1/privacy/deletions:preview' $privacyPreviewHeaders;Expect 400 {Api 'POST' '/api/v1/privacy/deletions:confirm' ($intruderHeaders+@{'Idempotency-Key'="p9-bad-$($seed.suffix)"}) @{requestId=$privacyPreview.data.requestId;requestVersion=$privacyPreview.data.requestVersion;confirmationPhrase='DELETE'}}'Privacy exact phrase'
 $privacyConfirmHeaders=$intruderHeaders.Clone();$privacyConfirmHeaders['Idempotency-Key']="p9-delete-confirm-$($seed.suffix)";$deleted=Api 'POST' '/api/v1/privacy/deletions:confirm' $privacyConfirmHeaders @{requestId=$privacyPreview.data.requestId;requestVersion=$privacyPreview.data.requestVersion;confirmationPhrase='DELETE MY JOBPILOT DATA'};Assert($deleted.data.status-eq'COMPLETED'-and$deleted.data.userDisabled)'Privacy deletion failed';Expect 401 {Login 'phase9_privacy' $intruderPassword}'Deleted account login'
 @{offerId=$o1.data.id;comparisonId=$comparison.data.id;snapshotId=$snapshot.data.id;createdAt=[DateTimeOffset]::UtcNow.ToString('o')}|ConvertTo-Json -Compress|Set-Content -LiteralPath $statePath -Encoding UTF8
 [pscustomobject]@{status='PASS';mode='FULL';httpCount=31;offersCreated=4;comparisonVersions=2;analyticsDimensions=@($analytics.data.dimensions.PSObject.Properties).Count;privacyDeletion='PASS';ownership='PASS';logicalDelete='PASS';externalMessagesSent=0;automaticOfferDecisions=0;fabricatedExchangeRates=0}|ConvertTo-Json -Compress
}finally{Pop-Location;$password=$null;$intruderPassword=$null}
