param([switch]$VerifyPersistence)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$baseUrl = 'http://127.0.0.1:8088'
$statePath = Join-Path $projectRoot 'scripts\.phase10-smoke-state.json'
$script:httpCount = 0

function Read-Env([string]$Name) { $line=Get-Content -LiteralPath (Join-Path $projectRoot '.env')|Where-Object{$_ -match ('^\s*'+[regex]::Escape($Name)+'\s*=')}|Select-Object -Last 1;if(-not $line){throw "Missing local environment value: $Name"};$value=($line -split '=',2)[1].Trim();if(($value.StartsWith('"')-and$value.EndsWith('"'))-or($value.StartsWith("'")-and$value.EndsWith("'"))){$value=$value.Substring(1,$value.Length-2)};return $value }
function New-Password([string]$Scope) { $sha=[Security.Cryptography.SHA256]::Create();try{$hex=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes("$Scope|$(Read-Env 'JWT_SECRET')")))).Replace('-','');return "P10!$($hex.Substring(0,30))z"}finally{$sha.Dispose()} }
function New-Bcrypt([string]$Password) { $crypto=Get-ChildItem "$env:USERPROFILE\.m2\repository\org\springframework\security\spring-security-crypto" -Recurse -Filter 'spring-security-crypto-*.jar'|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$jcl=Get-ChildItem "$env:USERPROFILE\.m2\repository\org\springframework\spring-jcl" -Recurse -Filter 'spring-jcl-*.jar'|Sort-Object LastWriteTime -Descending|Select-Object -First 1;$env:JOBPILOT_RESET_PASSWORD=$Password;try{$value=((& java --class-path ($crypto.FullName+';'+$jcl.FullName) (Join-Path $PSScriptRoot 'GenerateBcrypt.java'))-join '').Trim()}finally{Remove-Item Env:JOBPILOT_RESET_PASSWORD -ErrorAction SilentlyContinue};if($value-notmatch '^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$'){throw 'BCrypt generation failed'};return $value }
function Public-Id([string]$Prefix) { return ($Prefix+[Guid]::NewGuid().ToString('N')).Substring(0,26).ToUpperInvariant() }
function Api([string]$Method,[string]$Path,[hashtable]$Headers,$Body=$null) { $script:httpCount++;$p=@{Method=$Method;Uri="$baseUrl$Path";Headers=$Headers;TimeoutSec=120};if($null-ne$Body){$p.ContentType='application/json';$p.Body=$Body|ConvertTo-Json -Depth 30 -Compress};return Invoke-RestMethod @p }
function Assert([bool]$Condition,[string]$Message) { if(-not $Condition){throw $Message} }
function Expect([int]$Status,[scriptblock]$Action,[string]$Label) { try{$null=&$Action;throw "$Label unexpectedly succeeded"}catch{$actual=[int]$_.Exception.Response.StatusCode;if($actual-ne$Status){throw "$Label expected HTTP $Status but received $actual"}} }
function Login([string]$Name,[string]$Password) { return Api 'POST' '/api/v1/auth/login' @{} @{login=$Name;password=$Password} }
function Sql([string]$Text) { $Text|docker compose exec -T mysql sh -lc 'MYSQL_PWD="$MYSQL_PASSWORD" mysql -u"$MYSQL_USER" "$MYSQL_DATABASE"';if($LASTEXITCODE-ne0){throw 'Phase 10 SQL failed'} }

function Seed([string]$Password,[string]$IntruderPassword) {
  $hash=New-Bcrypt $Password;$intruderHash=New-Bcrypt $IntruderPassword;$suffix=[Guid]::NewGuid().ToString('N').Substring(0,12)
  $userPublic=Public-Id 'P10U';$intruderPublic=Public-Id 'P10I';$profilePublic=Public-Id 'P10P';$resumePublic=Public-Id 'P10R';$versionPublic=Public-Id 'P10V';$companyPublic=Public-Id 'P10C';$configPublic=Public-Id 'P10G'
  $sql=[Text.StringBuilder]::new()
  [void]$sql.AppendLine("INSERT INTO users(public_id,username,email,password_hash,display_name,status,created_at,updated_at) VALUES('$userPublic','phase10_smoke','phase10-smoke@local.invalid','$hash','Phase 10 Smoke','ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),status='ACTIVE',deleted_at=NULL,updated_at=UTC_TIMESTAMP(3);")
  [void]$sql.AppendLine("INSERT INTO users(public_id,username,email,password_hash,display_name,status,created_at,updated_at) VALUES('$intruderPublic','phase10_intruder','phase10-intruder@local.invalid','$intruderHash','Phase 10 Intruder','ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),status='ACTIVE',deleted_at=NULL,updated_at=UTC_TIMESTAMP(3);")
  [void]$sql.AppendLine("SET @uid=(SELECT id FROM users WHERE username='phase10_smoke'); DELETE FROM refresh_tokens WHERE user_id=@uid;")
  [void]$sql.AppendLine("INSERT INTO candidate_profiles(public_id,user_id,full_name,target_cities_json,target_roles_json,target_industries_json,target_company_types_json,salary_currency,accept_remote,accept_relocation,profile_completeness,created_at,updated_at) SELECT '$profilePublic',@uid,'Phase 10 Smoke',JSON_ARRAY('Shanghai'),JSON_ARRAY('Java Backend'),JSON_ARRAY(),JSON_ARRAY(),'CNY',1,0,60,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE NOT EXISTS(SELECT 1 FROM candidate_profiles WHERE user_id=@uid AND deleted_at IS NULL); SET @pid=(SELECT id FROM candidate_profiles WHERE user_id=@uid AND deleted_at IS NULL LIMIT 1);")
  [void]$sql.AppendLine("INSERT INTO resumes(public_id,user_id,name,target_role,master,default_resume,status,created_at,updated_at) SELECT '$resumePublic',@uid,'Phase 10 Master','Java Backend',1,1,'ACTIVE',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE NOT EXISTS(SELECT 1 FROM resumes WHERE user_id=@uid AND deleted_at IS NULL); SET @rid=(SELECT id FROM resumes WHERE user_id=@uid AND deleted_at IS NULL LIMIT 1);")
  [void]$sql.AppendLine("INSERT INTO resume_versions(public_id,resume_id,version_number,version_name,content_json,rendered_text,source_type,created_by,active,content_hash,created_at,updated_at) SELECT '$versionPublic',@rid,1,'Phase 10 v1','{}','Java Spring Boot MySQL Redis','MANUAL','USER',1,SHA2('phase10-resume',256),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3) WHERE NOT EXISTS(SELECT 1 FROM resume_versions WHERE resume_id=@rid); SET @rvid=(SELECT id FROM resume_versions WHERE resume_id=@rid ORDER BY version_number LIMIT 1); UPDATE resumes SET current_version_id=@rvid WHERE id=@rid;")
  [void]$sql.AppendLine("INSERT INTO companies(public_id,normalized_name,display_name,risk_flags_json,created_at,updated_at) VALUES('$companyPublic','phase10-$suffix','Phase 10 Company','[]',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @cid=LAST_INSERT_ID();")
  [void]$sql.AppendLine("INSERT INTO match_configs(public_id,user_id,name,version_no,weights_json,level_thresholds_json,penalties_json,algorithm_version,active,effective_at,created_at,updated_at) VALUES('$configPublic',@uid,'Phase 10 baseline',1,JSON_OBJECT('skill',30,'embedding',20,'llm',25,'project',10,'preference',10,'company',5),JSON_OBJECT('S',90,'A',80,'B',70),JSON_OBJECT(),'phase10-fixture',1,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @cfg=LAST_INSERT_ID();")
  $recommendations=@()
  for($i=1;$i-le36;$i++){
    $job=Public-Id 'P10J';$run=Public-Id 'P10N';$match=Public-Id 'P10M';$rec=Public-Id 'P10Q';$event=Public-Id 'P10E';$recommendations+=$rec;$score=44+$i;$ago=50-$i;$pair=[math]::Floor(($i-1)/2)
    [void]$sql.AppendLine("INSERT INTO jobs(public_id,user_id,company_id,title,normalized_title,canonical_job_key,fingerprint_hash,city,remote_type,salary_min,salary_max,salary_months,currency,job_type,description_raw,description_clean,responsibilities_json,requirements_json,first_collected_at,last_collected_at,status,parse_status,raw_content_hash,parse_result_json,manual_fields_json,created_at,updated_at) VALUES('$job',@uid,@cid,'Phase 10 Java Engineer $i','java backend',SHA2(CONCAT('phase10-pair-','$pair','$suffix'),256),SHA2(CONCAT('phase10-job-','$i','$suffix'),256),'Shanghai','HYBRID',20000,40000,13,'CNY','FULL_TIME','Java Spring Boot MySQL Redis','Java Spring Boot MySQL Redis','[]','[]',DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),UTC_TIMESTAMP(3),'ACTIVE','SUCCESS',SHA2(CONCAT('raw','$i','$suffix'),256),'{}','{}',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @job=LAST_INSERT_ID();")
    [void]$sql.AppendLine("INSERT INTO match_runs(public_id,user_id,job_id,candidate_profile_id,resume_version_id,match_config_id,idempotency_key,input_hash,force_run,status,attempt_count,max_attempts,available_at,started_at,finished_at,trace_id,created_at,updated_at) VALUES('$run',@uid,@job,@pid,@rvid,@cfg,'p10-run-$i-$suffix',SHA2(CONCAT('input','$i','$suffix'),256),0,'SUCCEEDED',1,3,UTC_TIMESTAMP(3),DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),'phase10-smoke',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @run=LAST_INSERT_ID();")
    [void]$sql.AppendLine("INSERT INTO job_matches(public_id,user_id,job_id,candidate_profile_id,resume_version_id,match_config_id,match_run_id,input_hash,hard_filter_result,hard_filter_json,skill_score,embedding_score,llm_score,project_score,preference_score,company_score,penalty_score,overall_score,level_code,advantages_json,gaps_json,risks_json,recommendation,reason_text,recommended_resume_version_id,algorithm_version,config_version,weights_snapshot_json,thresholds_snapshot_json,effective_weights_json,embedding_provider,embedding_model,embedding_version,llm_status,status,evaluated_at,created_at,updated_at) VALUES('$match',@uid,@job,@pid,@rvid,@cfg,@run,SHA2(CONCAT('match','$i','$suffix'),256),'PASS','{}',$score,$score,$score,$score,$score,$score,0,$score,'B','[]','[]','[]','RECOMMEND','Phase 10 historical evidence',@rvid,'phase10-fixture',1,'{}','{}','{}','fixture','fixture-v1','v1','SUCCEEDED','SUCCEEDED',DATE_SUB(DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),INTERVAL 1 HOUR),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @match=LAST_INSERT_ID(); UPDATE match_runs SET result_match_id=@match WHERE id=@run;")
    [void]$sql.AppendLine("INSERT INTO job_recommendations(public_id,user_id,job_id,latest_match_id,recommendation_status,favorite,rank_score,rank_version,rank_basis_json,last_evaluated_at,created_at,updated_at) VALUES('$rec',@uid,@job,@match,'READY',0,$score,'recommendation-v1','{}',DATE_SUB(DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),INTERVAL 1 HOUR),UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)); SET @rec=LAST_INSERT_ID();")
    [void]$sql.AppendLine("INSERT INTO recommendation_events(public_id,user_id,recommendation_id,job_id,job_match_id,event_type,previous_state_json,current_state_json,feature_snapshot_json,trace_id,occurred_at,created_at) VALUES('$event',@uid,@rec,@job,@match,'VIEWED','{}','{}','{}','phase10-smoke',DATE_SUB(UTC_TIMESTAMP(3),INTERVAL $ago DAY),UTC_TIMESTAMP(3));")
  }
  Sql $sql.ToString();return @{suffix=$suffix;recommendations=$recommendations}
}

Push-Location $projectRoot
try {
  Assert((Invoke-RestMethod "$baseUrl/actuator/health" -TimeoutSec 8).status-eq'UP') 'Backend is unavailable';Assert((docker compose exec -T redis redis-cli ping)-match'PONG') 'Redis is unavailable'
  $password=New-Password 'phase10-smoke';$intruderPassword=New-Password 'phase10-intruder'
  if($VerifyPersistence){$state=Get-Content -LiteralPath $statePath -Raw|ConvertFrom-Json;$login=Login 'phase10_smoke' $password;$headers=@{Authorization="Bearer $($login.data.accessToken)"};$model=Api 'GET' "/api/v1/learning/models/$($state.modelId)" $headers;$task=Api 'GET' "/api/v1/automation-center/tasks/$($state.taskId)" $headers;$dashboard=Api 'GET' '/api/v1/automation-center/dashboard' $headers;Assert($model.data.id-eq$state.modelId)'Persisted model missing';Assert($task.data.id-eq$state.taskId)'Persisted task missing';Assert($dashboard.data.schedulerEnabled-eq$false)'Safe scheduler default changed';[pscustomobject]@{status='PASS';mode='PERSISTENCE';httpCount=$script:httpCount;modelId=$state.modelId;taskId=$state.taskId}|ConvertTo-Json -Compress;exit 0}
  if(Test-Path -LiteralPath $statePath){throw 'Existing Phase 10 smoke state found. Use -VerifyPersistence after restart or remove it only with a clean Phase 10 smoke database.'}
  $seed=Seed $password $intruderPassword;$login=Login 'phase10_smoke' $password;$intruder=Login 'phase10_intruder' $intruderPassword;$headers=@{Authorization="Bearer $($login.data.accessToken)";'X-Trace-Id'="phase10-$([Guid]::NewGuid().ToString('N'))"};$intruderHeaders=@{Authorization="Bearer $($intruder.data.accessToken)"}
  $range=@{from=(Get-Date).AddDays(-365).ToString('yyyy-MM-dd');to=(Get-Date).ToString('yyyy-MM-dd')}
  $feedbackKey="p10-feedback-$($seed.suffix)";$h=$headers.Clone();$h['Idempotency-Key']=$feedbackKey;$rebuilt=Api 'POST' '/api/v1/learning/feedback:rebuild' $h $range;$replayed=Api 'POST' '/api/v1/learning/feedback:rebuild' $h $range;Assert($rebuilt.data.createdCount-ge36)'Feedback rebuild did not create 36 immutable samples';Assert($replayed.data.id-eq$rebuilt.data.id)'Feedback rebuild idempotency failed';Assert($rebuilt.data.leakageSafe)'Feedback leakage guard failed'
  $trainKey="p10-train-$($seed.suffix)";$h=$headers.Clone();$h['Idempotency-Key']=$trainKey;$trained=Api 'POST' '/api/v1/learning/models:train' $h @{from=$range.from;to=$range.to;name='Phase 10 Conservative Model'};$retrained=Api 'POST' '/api/v1/learning/models:train' $h @{from=$range.from;to=$range.to;name='Phase 10 Conservative Model'};Assert($trained.data.model.activationEligible)'Candidate model did not meet activation gate';Assert($retrained.data.run.id-eq$trained.data.run.id)'Training idempotency failed';Assert($trained.data.run.trainCount-eq28)'Chronological 80 percent split incorrect';Assert($trained.data.run.validationCount-eq8)'Chronological holdout count incorrect'
  $before=Api 'GET' '/api/v1/recommendations?limit=50' $headers;$shadowHeaders=$headers.Clone();$shadowHeaders['Idempotency-Key']="p10-shadow-$($seed.suffix)";$shadow=Api 'POST' "/api/v1/learning/models/$($trained.data.model.id):shadow" $shadowHeaders;$afterShadow=Api 'GET' '/api/v1/recommendations?limit=50' $headers;Assert($shadow.data.status-eq'SHADOW')'Shadow mode failed';Assert($shadow.data.shadowResults.Count-ge36)'Shadow results missing';Assert((@($afterShadow.data.items|Where-Object{$_.rankBasis.version-ne'recommendation-v1'}).Count-eq0))'Shadow changed live ranking'
  $active=Api 'POST' "/api/v1/learning/models/$($shadow.data.id):activate" $headers @{version=$shadow.data.version};$afterActive=Api 'GET' '/api/v1/recommendations?limit=50' $headers;Assert($active.data.status-eq'ACTIVE')'Explicit activation failed';Assert((@($afterActive.data.items|Where-Object{$_.rankBasis.modelVersion-eq1}).Count-ge36))'Active LTR did not project live rank';$rolled=Api 'POST' "/api/v1/learning/models/$($active.data.id):rollback" $headers @{version=$active.data.version};$afterRollback=Api 'GET' '/api/v1/recommendations?limit=50' $headers;Assert($rolled.data.rankingMode-eq'recommendation-v1')'Rollback did not select baseline';Assert((@($afterRollback.data.items|Where-Object{$_.rankBasis.version-ne'recommendation-v1'}).Count-eq0))'Baseline rank was not restored';Expect 404 {Api 'GET' "/api/v1/learning/models/$($active.data.id)" $intruderHeaders}'LTR ownership'
  $rule=Api 'POST' '/api/v1/automation-center/rules' $headers @{name='Duplicate review';ruleType='DUPLICATE_CLEANUP_SUGGESTION';scheduleExpression='0 0 9 * * *';timezone='Asia/Shanghai';config=@{};enabled=$false;maxAttempts=3};$runHeaders=$headers.Clone();$runHeaders['Idempotency-Key']="p10-rule-$($seed.suffix)";$task=Api 'POST' "/api/v1/automation-center/rules/$($rule.data.id):run" $runHeaders @{defer=$false};$taskReplay=Api 'POST' "/api/v1/automation-center/rules/$($rule.data.id):run" $runHeaders @{defer=$false};Assert($task.data.status-eq'SUCCEEDED')'Duplicate safe handler failed';Assert($taskReplay.data.id-eq$task.data.id)'Task idempotency failed';Assert((-not$task.data.externalMessageSent)-and(-not$task.data.externalSubmission)-and(-not$task.data.externalMutation)-and$task.data.userConfirmationRequired)'Task safety flags failed'
  $suggestionList=Api 'GET' '/api/v1/automation-center/suggestions?status=PENDING' $headers;Assert($suggestionList.data.Count-ge18)'Duplicate suggestions missing';$accepted=Api 'POST' "/api/v1/automation-center/suggestions/$($suggestionList.data[0].id):accept" $headers @{version=$suggestionList.data[0].version};Assert($accepted.data.status-eq'ACCEPTED')'Suggestion human decision failed'
  $digest=Api 'POST' '/api/v1/automation-center/rules' $headers @{name='Daily local digest';ruleType='DAILY_JOB_DIGEST';scheduleExpression='0 0 8 * * *';timezone='Asia/Shanghai';config=@{};enabled=$true;maxAttempts=3};$deferHeaders=$headers.Clone();$deferHeaders['Idempotency-Key']="p10-defer-$($seed.suffix)";$pending=Api 'POST' "/api/v1/automation-center/rules/$($digest.data.id):run" $deferHeaders @{defer=$true};$cancelled=Api 'POST' "/api/v1/automation-center/tasks/$($pending.data.id):cancel" $headers @{version=$pending.data.version};Assert($cancelled.data.status-eq'CANCELLED')'Pending task cancellation failed';$currentRules=Api 'GET' '/api/v1/automation-center/rules' $headers;$digestCurrent=$currentRules.data|Where-Object{$_.id-eq$digest.data.id}|Select-Object -First 1;$paused=Api 'PUT' "/api/v1/automation-center/rules/$($digest.data.id)" $headers @{version=$digestCurrent.version;enabled=$false};Assert($paused.data.status-eq'PAUSED')'Rule pause failed'
  $digestHeaders=$headers.Clone();$digestHeaders['Idempotency-Key']="p10-digest-$($seed.suffix)";$digestTask=Api 'POST' "/api/v1/automation-center/rules/$($digest.data.id):run" $digestHeaders @{defer=$false};$notifications=Api 'GET' '/api/v1/automation-center/notifications?status=UNREAD' $headers;Assert($notifications.data.Count-ge1)'In-app digest missing';$read=Api 'POST' "/api/v1/automation-center/notifications/$($notifications.data[0].id):read" $headers @{version=$notifications.data[0].version};Assert($read.data.status-eq'READ')'Notification read failed'
  $safeHandlers=@('SAFE_REEVALUATION','FOLLOW_UP_REMINDER','INTERVIEW_REMINDER','OFFER_DEADLINE_REMINDER');foreach($type in $safeHandlers){$config=if($type-eq'SAFE_REEVALUATION'){@{limit=1}}else{@{}};$handlerRule=Api 'POST' '/api/v1/automation-center/rules' $headers @{name="Handler $type";ruleType=$type;scheduleExpression='0 15 9 * * *';timezone='Asia/Shanghai';config=$config;enabled=$false;maxAttempts=3};$handlerHeaders=$headers.Clone();$handlerHeaders['Idempotency-Key']="p10-handler-$type-$($seed.suffix)";$handlerTask=Api 'POST' "/api/v1/automation-center/rules/$($handlerRule.data.id):run" $handlerHeaders @{defer=$false};Assert($handlerTask.data.status-eq'SUCCEEDED')"Safe handler $type failed"}
  $retryRule=Api 'POST' '/api/v1/automation-center/rules' $headers @{name='Retryable high match';ruleType='HIGH_MATCH_REMINDER';scheduleExpression='0 30 9 * * *';timezone='Asia/Shanghai';config=@{threshold='invalid'};enabled=$false;maxAttempts=3};$retryHeaders=$headers.Clone();$retryHeaders['Idempotency-Key']="p10-retry-$($seed.suffix)";$failedTask=Api 'POST' "/api/v1/automation-center/rules/$($retryRule.data.id):run" $retryHeaders @{defer=$false};Assert(($failedTask.data.status-eq'FAILED')-and($null-ne$failedTask.data.nextRetryAt))'Failure backoff state missing';$currentRules=Api 'GET' '/api/v1/automation-center/rules' $headers;$retryCurrent=$currentRules.data|Where-Object{$_.id-eq$retryRule.data.id}|Select-Object -First 1;$null=Api 'PUT' "/api/v1/automation-center/rules/$($retryRule.data.id)" $headers @{version=$retryCurrent.version;config=@{threshold=80}};$retried=Api 'POST' "/api/v1/automation-center/tasks/$($failedTask.data.id):retry" $headers @{version=$failedTask.data.version};Assert(($retried.data.status-eq'SUCCEEDED')-and($retried.data.attemptCount-eq2))'Safe task retry failed'
  $policy=Api 'PUT' '/api/v1/platform-policies/FIXTURE' $headers @{collectionMode='VISIBLE_PAGE_ONLY';applicationMode='ASSIST_ALLOWED';requiresFinalConfirmation=$true;policySourceUrl='https://example.invalid/manual-policy-evidence'};$expiry=(Get-Date).AddDays(30).ToString('yyyy-MM-ddTHH:mm:ss');$authorization=Api 'POST' '/api/v1/automation-center/authorizations' $headers @{platform='FIXTURE';scopes=@('MATCH_REFRESH','NOTIFICATION_WRITE','EXTERNAL_MESSAGE');evidenceType='MANUAL_REVIEW';evidenceRef='phase10-smoke-policy-review';expiresAt=$expiry};$localDecision=Api 'GET' '/api/v1/automation-center/policy-decision?platform=FIXTURE&scope=MATCH_REFRESH' $headers;$externalDecision=Api 'GET' '/api/v1/automation-center/policy-decision?platform=FIXTURE&scope=EXTERNAL_MESSAGE' $headers;Assert($localDecision.data.allowed-and$localDecision.data.executionMode-eq'LOCAL_SAFE')'Local authorization decision failed';Assert((-not$externalDecision.data.allowed)-and$externalDecision.data.executionMode-eq'MANUAL_ONLY')'External scope was not blocked';$revoked=Api 'DELETE' "/api/v1/automation-center/authorizations/$($authorization.data.id)" $headers;$afterRevoke=Api 'GET' '/api/v1/automation-center/policy-decision?platform=FIXTURE&scope=MATCH_REFRESH' $headers;Assert((-not$afterRevoke.data.allowed)-and$revoked.data.status-eq'REVOKED')'Authorization revocation downgrade failed';Expect 404 {Api 'GET' "/api/v1/automation-center/tasks/$($task.data.id)" $intruderHeaders}'Automation ownership'
  $dash=Api 'GET' '/api/v1/automation-center/dashboard' $headers;Assert((-not$dash.data.schedulerEnabled))'Scheduler must default off';$state=[ordered]@{modelId=$active.data.id;taskId=$task.data.id;feedbackRunId=$rebuilt.data.id};$state|ConvertTo-Json|Set-Content -LiteralPath $statePath -Encoding UTF8
  [pscustomobject]@{status='PASS';mode='FULL';httpCount=$script:httpCount;feedback=$rebuilt.data.createdCount;models=1;shadowRows=$shadow.data.shadowResults.Count;suggestions=$suggestionList.data.Count;schedulerEnabled=$dash.data.schedulerEnabled;externalActions=0}|ConvertTo-Json -Compress
} finally { Pop-Location;$password=$null;$intruderPassword=$null }
