package com.jobpilot.automation.service;

import static com.jobpilot.automation.dto.AutomationCenterDtos.*;
import com.jobpilot.recommendation.dto.RecommendationDtos.RecommendationRefreshRequest;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jobpilot.application.domain.ApplicationEntity;
import com.jobpilot.application.mapper.ApplicationMapper;
import com.jobpilot.audit.service.AuditService;
import com.jobpilot.automation.domain.AutomationNotificationEntity;
import com.jobpilot.automation.domain.AutomationRuleEntity;
import com.jobpilot.automation.domain.AutomationSuggestionEntity;
import com.jobpilot.automation.domain.SafeAutomationTaskEntity;
import com.jobpilot.automation.mapper.AutomationNotificationMapper;
import com.jobpilot.automation.mapper.AutomationRuleMapper;
import com.jobpilot.automation.mapper.AutomationSuggestionMapper;
import com.jobpilot.automation.mapper.SafeAutomationTaskMapper;
import com.jobpilot.common.exception.BusinessException;
import com.jobpilot.common.exception.ResourceNotFoundException;
import com.jobpilot.common.exception.ValidationException;
import com.jobpilot.common.logging.TraceContext;
import com.jobpilot.common.util.JsonCodec;
import com.jobpilot.interview.domain.InterviewReminderEntity;
import com.jobpilot.interview.mapper.InterviewReminderMapper;
import com.jobpilot.job.domain.JobEntity;
import com.jobpilot.job.mapper.JobMapper;
import com.jobpilot.learning.service.LearningHash;
import com.jobpilot.matching.domain.JobMatchEntity;
import com.jobpilot.matching.mapper.JobMatchMapper;
import com.jobpilot.offer.domain.OfferDeadlineEntity;
import com.jobpilot.offer.mapper.OfferDeadlineMapper;
import com.jobpilot.recommendation.service.RecommendationRefreshService;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.scheduling.support.CronExpression;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AutomationCenterService {
    public static final Set<String> RULE_TYPES=Set.of("DAILY_JOB_DIGEST","SAFE_REEVALUATION","DUPLICATE_CLEANUP_SUGGESTION","HIGH_MATCH_REMINDER","FOLLOW_UP_REMINDER","INTERVIEW_REMINDER","OFFER_DEADLINE_REMINDER");
    private static final Set<String> TASK_STATUSES=Set.of("PENDING","RUNNING","SUCCEEDED","FAILED","BLOCKED","CANCELLED");
    private final AutomationRuleMapper rules;private final SafeAutomationTaskMapper tasks;private final AutomationSuggestionMapper suggestions;private final AutomationNotificationMapper notifications;
    private final JobMapper jobs;private final JobMatchMapper matches;private final ApplicationMapper applications;private final InterviewReminderMapper interviewReminders;private final OfferDeadlineMapper offerDeadlines;
    private final RecommendationRefreshService refresh;private final ObjectMapper objectMapper;private final JsonCodec json;private final AuditService audit;private final boolean schedulerEnabled;
    public AutomationCenterService(AutomationRuleMapper rules,SafeAutomationTaskMapper tasks,AutomationSuggestionMapper suggestions,AutomationNotificationMapper notifications,JobMapper jobs,JobMatchMapper matches,ApplicationMapper applications,InterviewReminderMapper interviewReminders,OfferDeadlineMapper offerDeadlines,RecommendationRefreshService refresh,ObjectMapper objectMapper,JsonCodec json,AuditService audit,@Value("${jobpilot.automation-center.enabled:false}") boolean schedulerEnabled){this.rules=rules;this.tasks=tasks;this.suggestions=suggestions;this.notifications=notifications;this.jobs=jobs;this.matches=matches;this.applications=applications;this.interviewReminders=interviewReminders;this.offerDeadlines=offerDeadlines;this.refresh=refresh;this.objectMapper=objectMapper;this.json=json;this.audit=audit;this.schedulerEnabled=schedulerEnabled;}

    @Transactional public RuleView createRule(Long userId,RuleCreateRequest request){validateType(request.ruleType());schedule(request.scheduleExpression(),request.timezone());AutomationRuleEntity entity=new AutomationRuleEntity();entity.setUserId(userId);entity.setName(request.name().trim());entity.setRuleType(request.ruleType().trim().toUpperCase(Locale.ROOT));entity.setScheduleExpression(request.scheduleExpression().trim());entity.setTimezone(request.timezone().trim());entity.setConfigJson(json.write(request.config()==null?Map.of():request.config()));entity.setEnabled(Boolean.TRUE.equals(request.enabled()));entity.setStatus(entity.getEnabled()?"ACTIVE":"PAUSED");entity.setMaxAttempts(request.maxAttempts()==null?3:request.maxAttempts());entity.setNextRunAt(next(entity.getScheduleExpression(),entity.getTimezone()));rules.insert(entity);audit.record(userId,"AUTOMATION_RULE_CREATE","AUTOMATION_RULE",entity.getPublicId());return ruleView(entity);}
    public List<RuleView> listRules(Long userId){return rules.selectList(new LambdaQueryWrapper<AutomationRuleEntity>().eq(AutomationRuleEntity::getUserId,userId).orderByDesc(AutomationRuleEntity::getUpdatedAt)).stream().map(this::ruleView).toList();}
    @Transactional public RuleView updateRule(Long userId,String id,RuleUpdateRequest request){AutomationRuleEntity entity=ownedRule(userId,id);version(entity.getVersion(),request.version());String cron=request.scheduleExpression()==null?entity.getScheduleExpression():request.scheduleExpression().trim(),zone=request.timezone()==null?entity.getTimezone():request.timezone().trim();schedule(cron,zone);if(request.name()!=null)entity.setName(request.name().trim());entity.setScheduleExpression(cron);entity.setTimezone(zone);if(request.config()!=null)entity.setConfigJson(json.write(request.config()));if(request.enabled()!=null){entity.setEnabled(request.enabled());entity.setStatus(request.enabled()?"ACTIVE":"PAUSED");}if(request.maxAttempts()!=null)entity.setMaxAttempts(request.maxAttempts());entity.setNextRunAt(next(cron,zone));if(rules.updateById(entity)!=1)conflict("Automation rule version conflict");audit.record(userId,"AUTOMATION_RULE_UPDATE","AUTOMATION_RULE",id);return ruleView(ownedRule(userId,id));}

    @Transactional public TaskView runRule(Long userId,String id,String key,RuleRunRequest request){validateKey(key);AutomationRuleEntity rule=ownedRule(userId,id);Map<String,Object> semantic=new LinkedHashMap<>();semantic.put("ruleId",id);semantic.put("type",rule.getRuleType());semantic.put("schedule",rule.getScheduleExpression());semantic.put("timezone",rule.getTimezone());semantic.put("config",config(rule));semantic.put("maxAttempts",rule.getMaxAttempts());String hash=LearningHash.sha256(json.write(semantic));SafeAutomationTaskEntity existing=tasks.selectOne(new LambdaQueryWrapper<SafeAutomationTaskEntity>().eq(SafeAutomationTaskEntity::getUserId,userId).eq(SafeAutomationTaskEntity::getIdempotencyKey,key.trim()).last("LIMIT 1"));if(existing!=null){if(!existing.getRequestHash().equals(hash))throw conflict("Task idempotency key was used with different semantic rule input");return taskView(existing);}
        SafeAutomationTaskEntity task=new SafeAutomationTaskEntity();task.setUserId(userId);task.setAutomationRuleId(rule.getId());task.setTaskType(rule.getRuleType());task.setIdempotencyKey(key.trim());task.setRequestHash(hash);task.setStatus("PENDING");task.setInputJson(json.write(Map.of("ruleId",id,"config",config(rule))));task.setOutputJson("{}");task.setAttemptCount(0);task.setMaxAttempts(rule.getMaxAttempts());task.setScheduledAt(LocalDateTime.now(ZoneOffset.UTC));task.setTraceId(TraceContext.getTraceId());task.setExternalMessageSent(false);task.setExternalSubmission(false);task.setExternalMutation(false);task.setUserConfirmationRequired(true);tasks.insert(task);audit.record(userId,"AUTOMATION_RULE_RUN","SAFE_AUTOMATION_TASK",task.getPublicId());if(request==null||!Boolean.TRUE.equals(request.defer()))execute(task,rule);rule.setLastRunAt(LocalDateTime.now(ZoneOffset.UTC));rule.setNextRunAt(next(rule.getScheduleExpression(),rule.getTimezone()));rules.updateById(rule);return taskView(ownedTask(userId,task.getPublicId()));}
    public List<TaskView> listTasks(Long userId,String status){LambdaQueryWrapper<SafeAutomationTaskEntity> query=new LambdaQueryWrapper<SafeAutomationTaskEntity>().eq(SafeAutomationTaskEntity::getUserId,userId).orderByDesc(SafeAutomationTaskEntity::getCreatedAt);if(status!=null&&!status.isBlank()){String value=status.trim().toUpperCase(Locale.ROOT);if(!TASK_STATUSES.contains(value))throw new ValidationException("Unsupported task status");query.eq(SafeAutomationTaskEntity::getStatus,value);}return tasks.selectList(query).stream().map(this::taskView).toList();}
    public TaskView task(Long userId,String id){return taskView(ownedTask(userId,id));}
    @Transactional public TaskView retry(Long userId,String id,int expectedVersion){SafeAutomationTaskEntity task=ownedTask(userId,id);version(task.getVersion(),expectedVersion);if(!List.of("FAILED","BLOCKED").contains(task.getStatus()))throw conflict("Only failed or blocked safe tasks can be retried");if(task.getAttemptCount()>=task.getMaxAttempts())throw conflict("Task retry limit has been reached");AutomationRuleEntity rule=ruleById(userId,task.getAutomationRuleId());task.setStatus("PENDING");task.setNextRetryAt(null);task.setErrorCode(null);task.setErrorMessageSafe(null);tasks.updateById(task);execute(task,rule);audit.record(userId,"AUTOMATION_TASK_RETRY","SAFE_AUTOMATION_TASK",id);return taskView(ownedTask(userId,id));}
    @Transactional public TaskView cancel(Long userId,String id,int expectedVersion){SafeAutomationTaskEntity task=ownedTask(userId,id);version(task.getVersion(),expectedVersion);if(!"PENDING".equals(task.getStatus()))throw conflict("Only pending safe tasks can be cancelled");task.setStatus("CANCELLED");task.setFinishedAt(LocalDateTime.now(ZoneOffset.UTC));tasks.updateById(task);audit.record(userId,"AUTOMATION_TASK_CANCEL","SAFE_AUTOMATION_TASK",id);return taskView(ownedTask(userId,id));}

    public List<SuggestionView> listSuggestions(Long userId,String status){LambdaQueryWrapper<AutomationSuggestionEntity> q=new LambdaQueryWrapper<AutomationSuggestionEntity>().eq(AutomationSuggestionEntity::getUserId,userId).orderByDesc(AutomationSuggestionEntity::getCreatedAt);if(status!=null&&!status.isBlank())q.eq(AutomationSuggestionEntity::getStatus,status.trim().toUpperCase(Locale.ROOT));return suggestions.selectList(q).stream().map(this::suggestionView).toList();}
    @Transactional public SuggestionView decideSuggestion(Long userId,String id,int expectedVersion,String status){AutomationSuggestionEntity value=ownedSuggestion(userId,id);version(value.getVersion(),expectedVersion);if(!"PENDING".equals(value.getStatus()))throw conflict("Suggestion already has a final decision");value.setStatus(status);value.setDecidedAt(LocalDateTime.now(ZoneOffset.UTC));suggestions.updateById(value);audit.record(userId,"AUTOMATION_SUGGESTION_"+status,"AUTOMATION_SUGGESTION",id);return suggestionView(ownedSuggestion(userId,id));}
    public List<NotificationView> listNotifications(Long userId,String status){LambdaQueryWrapper<AutomationNotificationEntity> q=new LambdaQueryWrapper<AutomationNotificationEntity>().eq(AutomationNotificationEntity::getUserId,userId).orderByDesc(AutomationNotificationEntity::getCreatedAt);if(status!=null&&!status.isBlank())q.eq(AutomationNotificationEntity::getStatus,status.trim().toUpperCase(Locale.ROOT));return notifications.selectList(q).stream().map(this::notificationView).toList();}
    @Transactional public NotificationView readNotification(Long userId,String id,int expectedVersion){AutomationNotificationEntity value=ownedNotification(userId,id);version(value.getVersion(),expectedVersion);if("UNREAD".equals(value.getStatus())){value.setStatus("READ");value.setReadAt(LocalDateTime.now(ZoneOffset.UTC));notifications.updateById(value);audit.record(userId,"AUTOMATION_NOTIFICATION_READ","AUTOMATION_NOTIFICATION",id);}return notificationView(ownedNotification(userId,id));}
    public AutomationDashboard dashboard(Long userId){return new AutomationDashboard(countRules(userId,true),countRules(userId,false),countTasks(userId,"PENDING"),countTasks(userId,"FAILED"),suggestions.selectCount(new LambdaQueryWrapper<AutomationSuggestionEntity>().eq(AutomationSuggestionEntity::getUserId,userId).eq(AutomationSuggestionEntity::getStatus,"PENDING")),notifications.selectCount(new LambdaQueryWrapper<AutomationNotificationEntity>().eq(AutomationNotificationEntity::getUserId,userId).eq(AutomationNotificationEntity::getStatus,"UNREAD")),schedulerEnabled,RULE_TYPES.stream().sorted().toList(),List.of("仅允许本地处理器","不会发送外部消息","不会进行外部投递","不会破坏性删除重复岗位","始终需要用户确认"));}

    public List<AutomationRuleEntity> dueRules(){if(!schedulerEnabled)return List.of();return rules.selectList(new LambdaQueryWrapper<AutomationRuleEntity>().eq(AutomationRuleEntity::getEnabled,true).eq(AutomationRuleEntity::getStatus,"ACTIVE").le(AutomationRuleEntity::getNextRunAt,LocalDateTime.now(ZoneOffset.UTC)).orderByAsc(AutomationRuleEntity::getNextRunAt).last("LIMIT 20"));}
    public void runScheduled(AutomationRuleEntity rule){runRule(rule.getUserId(),rule.getPublicId(),"scheduled:"+rule.getPublicId()+":"+rule.getNextRunAt(),new RuleRunRequest(false));}

    private void execute(SafeAutomationTaskEntity task,AutomationRuleEntity rule){task.setStatus("RUNNING");task.setAttemptCount(task.getAttemptCount()+1);task.setStartedAt(LocalDateTime.now(ZoneOffset.UTC));tasks.updateById(task);try{Map<String,Object> output=handler(task,rule);task.setOutputJson(json.write(output));task.setStatus("SUCCEEDED");task.setFinishedAt(LocalDateTime.now(ZoneOffset.UTC));task.setNextRetryAt(null);task.setErrorCode(null);task.setErrorMessageSafe(null);}catch(RuntimeException exception){task.setStatus("FAILED");task.setErrorCode("SAFE_HANDLER_FAILED");task.setErrorMessageSafe("Safe handler failed: "+exception.getClass().getSimpleName());task.setNextRetryAt(LocalDateTime.now(ZoneOffset.UTC).plusMinutes(1L<<Math.min(6,task.getAttemptCount()-1)));task.setFinishedAt(LocalDateTime.now(ZoneOffset.UTC));}tasks.updateById(task);}
    private Map<String,Object> handler(SafeAutomationTaskEntity task,AutomationRuleEntity rule){Map<String,Object> config=config(rule);return switch(rule.getRuleType()){
        case"DAILY_JOB_DIGEST"->dailyDigest(task,rule);
        case"SAFE_REEVALUATION"->safeReevaluation(task,rule,config);
        case"DUPLICATE_CLEANUP_SUGGESTION"->duplicateSuggestions(task,rule);
        case"HIGH_MATCH_REMINDER"->highMatch(task,rule,config);
        case"FOLLOW_UP_REMINDER"->followUp(task,rule,config);
        case"INTERVIEW_REMINDER"->interviewReminder(task,rule);
        case"OFFER_DEADLINE_REMINDER"->offerReminder(task,rule);
        default->throw new ValidationException("No safe handler exists for task type");};}
    private Map<String,Object> dailyDigest(SafeAutomationTaskEntity task,AutomationRuleEntity rule){long active=jobs.selectCount(new LambdaQueryWrapper<JobEntity>().eq(JobEntity::getUserId,task.getUserId()).eq(JobEntity::getStatus,"ACTIVE"));boolean created=notification(task,"DAILY_JOB_DIGEST","Daily JobPilot digest",active+" active jobs are available in your local workspace","JOB",null,"digest:"+LocalDate.now(ZoneId.of(rule.getTimezone())));return Map.of("activeJobs",active,"notificationCreated",created);}
    private Map<String,Object> safeReevaluation(SafeAutomationTaskEntity task,AutomationRuleEntity rule,Map<String,Object> config){int limit=integer(config,"limit",20,1,100);var result=refresh.start(task.getUserId(),new RecommendationRefreshRequest(false,null,null,null,false,limit,null),"automation:"+task.getPublicId());return Map.of("refreshRunId",result.id(),"status",result.status(),"totalCount",result.totalCount());}
    private Map<String,Object> duplicateSuggestions(SafeAutomationTaskEntity task,AutomationRuleEntity rule){List<JobEntity> values=jobs.selectList(new LambdaQueryWrapper<JobEntity>().eq(JobEntity::getUserId,task.getUserId()));Map<String,List<JobEntity>> groups=values.stream().filter(v->text(v.getCanonicalJobKey())||text(v.getFingerprintHash())).collect(Collectors.groupingBy(v->text(v.getCanonicalJobKey())?v.getCanonicalJobKey():v.getFingerprintHash()));int created=0;for(List<JobEntity> group:groups.values()){if(group.size()<2)continue;List<String> ids=group.stream().map(JobEntity::getPublicId).sorted().toList();if(suggestion(task,rule,"DUPLICATE_CLEANUP_SUGGESTION","JOB_GROUP",ids.getFirst(),"Review possible duplicate jobs",group.size()+" jobs share a stable duplicate key. Review them manually; no job was deleted.",Map.of("jobIds",ids,"count",group.size()),"duplicate:"+String.join(":",ids)))created++;}return Map.of("duplicateGroups",created,"destructiveDeletes",0);}
    private Map<String,Object> highMatch(SafeAutomationTaskEntity task,AutomationRuleEntity rule,Map<String,Object> config){BigDecimal threshold=new BigDecimal(String.valueOf(config.getOrDefault("threshold",80)));Map<Long,JobMatchEntity> latest=latestMatches(task.getUserId());Map<Long,JobEntity> jobById=jobs.selectList(new LambdaQueryWrapper<JobEntity>().eq(JobEntity::getUserId,task.getUserId())).stream().collect(Collectors.toMap(JobEntity::getId,Function.identity()));int created=0;for(JobMatchEntity match:latest.values()){if(match.getOverallScore()!=null&&match.getOverallScore().compareTo(threshold)>=0){JobEntity job=jobById.get(match.getJobId());if(notification(task,"HIGH_MATCH_REMINDER","High-match job",(job==null?"Job":job.getTitle())+" scored "+match.getOverallScore(),"JOB",job==null?null:job.getPublicId(),"high-match:"+match.getPublicId()))created++;}}return Map.of("notificationsCreated",created,"threshold",threshold);}
    private Map<String,Object> followUp(SafeAutomationTaskEntity task,AutomationRuleEntity rule,Map<String,Object> config){int days=integer(config,"days",7,1,90);LocalDateTime cutoff=LocalDateTime.now(ZoneOffset.UTC).minusDays(days);List<ApplicationEntity> due=applications.selectList(new LambdaQueryWrapper<ApplicationEntity>().eq(ApplicationEntity::getUserId,task.getUserId()).in(ApplicationEntity::getStatus,List.of("APPLIED","REPLIED")).le(ApplicationEntity::getLastStatusAt,cutoff));int created=0;for(ApplicationEntity app:due)if(notification(task,"FOLLOW_UP_REMINDER","申请需要跟进","进行任何人工外部操作前，请先在本地检查申请记录。","APPLICATION",app.getPublicId(),"follow-up:"+app.getPublicId()+":"+app.getStatus()))created++;return Map.of("notificationsCreated",created,"olderThanDays",days);}
    private Map<String,Object> interviewReminder(SafeAutomationTaskEntity task,AutomationRuleEntity rule){LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);List<InterviewReminderEntity> due=interviewReminders.selectList(new LambdaQueryWrapper<InterviewReminderEntity>().eq(InterviewReminderEntity::getUserId,task.getUserId()).eq(InterviewReminderEntity::getStatus,"PENDING").between(InterviewReminderEntity::getRemindAt,now,now.plusHours(24)));int created=0;for(InterviewReminderEntity item:due)if(notification(task,"INTERVIEW_REMINDER",item.getTitle(),"In-app interview reminder due at "+item.getRemindAt(),"INTERVIEW_REMINDER",item.getPublicId(),"interview:"+item.getPublicId()))created++;return Map.of("notificationsCreated",created,"windowHours",24);}
    private Map<String,Object> offerReminder(SafeAutomationTaskEntity task,AutomationRuleEntity rule){LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);List<OfferDeadlineEntity> due=offerDeadlines.selectList(new LambdaQueryWrapper<OfferDeadlineEntity>().eq(OfferDeadlineEntity::getUserId,task.getUserId()).eq(OfferDeadlineEntity::getStatus,"PENDING").between(OfferDeadlineEntity::getDueAt,now,now.plusDays(7)));int created=0;for(OfferDeadlineEntity item:due)if(notification(task,"OFFER_DEADLINE_REMINDER",item.getTitle(),"In-app Offer deadline due at "+item.getDueAt(),"OFFER_DEADLINE",item.getPublicId(),"offer:"+item.getPublicId()))created++;return Map.of("notificationsCreated",created,"windowDays",7,"automaticOfferDecisions",0);}

    private boolean suggestion(SafeAutomationTaskEntity task,AutomationRuleEntity rule,String type,String resourceType,String resourceId,String title,String body,Map<String,Object> evidence,String rawKey){String key=LearningHash.sha256(rawKey);if(suggestions.selectCount(new LambdaQueryWrapper<AutomationSuggestionEntity>().eq(AutomationSuggestionEntity::getUserId,task.getUserId()).eq(AutomationSuggestionEntity::getDedupKey,key))>0)return false;AutomationSuggestionEntity value=new AutomationSuggestionEntity();value.setUserId(task.getUserId());value.setAutomationRuleId(rule.getId());value.setTaskId(task.getId());value.setDedupKey(key);value.setSuggestionType(type);value.setResourceType(resourceType);value.setResourceId(resourceId);value.setTitle(title);value.setBody(body);value.setEvidenceJson(json.write(evidence));value.setStatus("PENDING");try{suggestions.insert(value);return true;}catch(DataIntegrityViolationException e){return false;}}
    private boolean notification(SafeAutomationTaskEntity task,String type,String title,String body,String resourceType,String resourceId,String rawKey){String key=LearningHash.sha256(rawKey);if(notifications.selectCount(new LambdaQueryWrapper<AutomationNotificationEntity>().eq(AutomationNotificationEntity::getUserId,task.getUserId()).eq(AutomationNotificationEntity::getDedupKey,key))>0)return false;AutomationNotificationEntity value=new AutomationNotificationEntity();value.setUserId(task.getUserId());value.setTaskId(task.getId());value.setDedupKey(key);value.setNotificationType(type);value.setTitle(title);value.setBody(body);value.setResourceType(resourceType);value.setResourceId(resourceId);value.setStatus("UNREAD");try{notifications.insert(value);return true;}catch(DataIntegrityViolationException e){return false;}}
    private Map<Long,JobMatchEntity> latestMatches(Long userId){Map<Long,JobMatchEntity> result=new LinkedHashMap<>();matches.selectList(new LambdaQueryWrapper<JobMatchEntity>().eq(JobMatchEntity::getUserId,userId).orderByDesc(JobMatchEntity::getEvaluatedAt).orderByDesc(JobMatchEntity::getId)).forEach(v->result.putIfAbsent(v.getJobId(),v));return result;}
    private Map<String,Object> config(AutomationRuleEntity rule){try{return objectMapper.readValue(rule.getConfigJson(),new TypeReference<LinkedHashMap<String,Object>>(){});}catch(Exception e){throw new IllegalStateException("Stored automation config is invalid",e);}}
    private RuleView ruleView(AutomationRuleEntity v){return new RuleView(v.getPublicId(),v.getVersion(),v.getName(),v.getRuleType(),v.getScheduleExpression(),v.getTimezone(),json.readNode(v.getConfigJson()),Boolean.TRUE.equals(v.getEnabled()),v.getStatus(),v.getMaxAttempts(),v.getLastRunAt(),v.getNextRunAt(),v.getCreatedAt());}
    private TaskView taskView(SafeAutomationTaskEntity v){return new TaskView(v.getPublicId(),v.getVersion(),rules.selectById(v.getAutomationRuleId()).getPublicId(),v.getTaskType(),v.getStatus(),v.getAttemptCount(),v.getMaxAttempts(),json.readNode(v.getInputJson()),json.readNode(v.getOutputJson()),v.getScheduledAt(),v.getNextRetryAt(),v.getStartedAt(),v.getFinishedAt(),v.getErrorCode(),v.getErrorMessageSafe(),Boolean.TRUE.equals(v.getExternalMessageSent()),Boolean.TRUE.equals(v.getExternalSubmission()),Boolean.TRUE.equals(v.getExternalMutation()),Boolean.TRUE.equals(v.getUserConfirmationRequired()),v.getCreatedAt());}
    private SuggestionView suggestionView(AutomationSuggestionEntity v){return new SuggestionView(v.getPublicId(),v.getVersion(),v.getSuggestionType(),v.getResourceType(),v.getResourceId(),v.getTitle(),v.getBody(),json.readNode(v.getEvidenceJson()),v.getStatus(),v.getDecidedAt(),v.getCreatedAt());}
    private NotificationView notificationView(AutomationNotificationEntity v){return new NotificationView(v.getPublicId(),v.getVersion(),v.getNotificationType(),v.getTitle(),v.getBody(),v.getResourceType(),v.getResourceId(),v.getStatus(),v.getReadAt(),v.getCreatedAt());}
    private AutomationRuleEntity ownedRule(Long userId,String id){AutomationRuleEntity value=rules.selectOne(new LambdaQueryWrapper<AutomationRuleEntity>().eq(AutomationRuleEntity::getUserId,userId).eq(AutomationRuleEntity::getPublicId,id).last("LIMIT 1"));if(value==null)throw new ResourceNotFoundException("Automation rule");return value;}
    private AutomationRuleEntity ruleById(Long userId,Long id){AutomationRuleEntity value=rules.selectOne(new LambdaQueryWrapper<AutomationRuleEntity>().eq(AutomationRuleEntity::getUserId,userId).eq(AutomationRuleEntity::getId,id).last("LIMIT 1"));if(value==null)throw new ResourceNotFoundException("Automation rule");return value;}
    private SafeAutomationTaskEntity ownedTask(Long userId,String id){SafeAutomationTaskEntity value=tasks.selectOne(new LambdaQueryWrapper<SafeAutomationTaskEntity>().eq(SafeAutomationTaskEntity::getUserId,userId).eq(SafeAutomationTaskEntity::getPublicId,id).last("LIMIT 1"));if(value==null)throw new ResourceNotFoundException("Safe automation task");return value;}
    private AutomationSuggestionEntity ownedSuggestion(Long userId,String id){AutomationSuggestionEntity value=suggestions.selectOne(new LambdaQueryWrapper<AutomationSuggestionEntity>().eq(AutomationSuggestionEntity::getUserId,userId).eq(AutomationSuggestionEntity::getPublicId,id).last("LIMIT 1"));if(value==null)throw new ResourceNotFoundException("Automation suggestion");return value;}
    private AutomationNotificationEntity ownedNotification(Long userId,String id){AutomationNotificationEntity value=notifications.selectOne(new LambdaQueryWrapper<AutomationNotificationEntity>().eq(AutomationNotificationEntity::getUserId,userId).eq(AutomationNotificationEntity::getPublicId,id).last("LIMIT 1"));if(value==null)throw new ResourceNotFoundException("Automation notification");return value;}
    private long countRules(Long userId,boolean enabled){return rules.selectCount(new LambdaQueryWrapper<AutomationRuleEntity>().eq(AutomationRuleEntity::getUserId,userId).eq(AutomationRuleEntity::getEnabled,enabled));}
    private long countTasks(Long userId,String status){return tasks.selectCount(new LambdaQueryWrapper<SafeAutomationTaskEntity>().eq(SafeAutomationTaskEntity::getUserId,userId).eq(SafeAutomationTaskEntity::getStatus,status));}
    public static LocalDateTime next(String cron,String timezone){try{CronExpression expression=CronExpression.parse(cron);ZoneId zone=ZoneId.of(timezone);ZonedDateTime next=expression.next(ZonedDateTime.now(zone));if(next==null)throw new ValidationException("Cron expression has no next execution");return LocalDateTime.ofInstant(next.toInstant(),ZoneOffset.UTC);}catch(ValidationException e){throw e;}catch(Exception e){throw new ValidationException("Invalid Spring cron expression or IANA timezone");}}
    static void schedule(String cron,String timezone){next(cron,timezone);}
    private static int integer(Map<String,Object> config,String key,int fallback,int min,int max){Object raw=config.get(key);if(raw==null)return fallback;try{int value=Integer.parseInt(String.valueOf(raw));if(value<min||value>max)throw new NumberFormatException();return value;}catch(NumberFormatException e){throw new ValidationException(key+" must be between "+min+" and "+max);}}
    private static void validateType(String value){if(value==null||!RULE_TYPES.contains(value.trim().toUpperCase(Locale.ROOT)))throw new ValidationException("Unsupported automation rule type");}
    private static void validateKey(String value){if(value==null||value.isBlank()||value.length()>120)throw new ValidationException("Idempotency-Key is required and must be at most 120 characters");}
    private static void version(Integer current,Integer expected){if(expected==null||!current.equals(expected))throw conflict("Resource version conflict");}
    private static BusinessException conflict(String message){return new BusinessException(4091030,message,HttpStatus.CONFLICT);}
    private static boolean text(String value){return value!=null&&!value.isBlank();}
}
